### ISSUE TITLE
[Plugin-related] [Drag-n-Drop] Checkbox is not functional in editing view

### ISSUE THREAD

**Issue by bagameow** [AnubisNekhet/AnuPpuccin#1]
It looks like checkbox can't be triggered in editing view.

**Comment by AnubisNekhet** [comment]
Can you send a screenshot of your issue?

**Comment by bagameow** [comment]
Hi, I've confirmed this is caused by another plugin "Drag-n-Drop for blocks".
Here is how to reproduce.
- Display both left and right sidebar
- split current document vertically (so there will be four pane including two siderbars)
- create a checkbox and perhaps you can observe the checkbox can't be triggered.

Since this is caused by combination with another plugin, I guess if you are curious, you can check on this :) 
It will be ok to just close this issue.

**Comment by AnubisNekhet** [comment]
I've tried out the plugin an so far, I can't see any problem, since it works both with and without the theme. I'll still keep this issue open in case I do encounter it in the issue or someone else who has had this problem provides a solution.

**Comment by AnubisNekhet** [comment]
Seeing how there hasn't been any problems, I'll close this issue.
