### ISSUE TITLE
FR: Folder color customization!

### ISSUE THREAD

**Issue by brimwats** [AnubisNekhet/AnuPpuccin#1]
I'd love to have a way to customize my folder colors if possible, perhaps stylesettings?

here's what I use currently if it's helpful for that:

```css
    /* folder colours */
	--Fold_: 					var(--bright-blue);
	--Fold0: 					rgba(189, 174, 147, 0.7);
	--Fold0File: 					rgba(189, 174, 147, 0.3);
    --Fold1:		rgba(66, 184, 164, 0.7);
    --Fold1File:		rgba(66, 184, 164, 0.5);
    --Fold2:		rgba(223, 69, 58, 0.7);
    --Fold2File:		rgba(223, 69, 58, 0.5);
    --Fold3:		rgba(216, 121, 213, 0.7);
    --Fold3File:		rgba(216, 121, 213, 0.5);
    --Fold4:		rgba(141, 111, 179, 0.7);
    --Fold4File:		rgba(141, 111, 179, 0.5);
    --Fold5:		rgba(235, 112, 46, 0.7);
    --Fold5File:		rgba(235, 112, 46, 0.5);
    --Fold6:		rgba(227, 173, 38, 0.7);
    --Fold6File:		rgba(227, 173, 38, 0.5);
	--FoldZ: 					#a9a9a9cc;
	--FoldI: 					#1976d2CC;
	--Fold7: 					#c2185bCC;
	--Fold8: 					#00796bCC;
	--Fold9: 					#388e3cCC;
	--FoldA: 					#303f9fCC;
	--FoldB: 					#afb42bCC;
	--FoldZ: 					#7c6f64;
	--FoldM: 					#4fca31cc;
	--FoldText: 				rgb(40, 40, 40);
}

/* 000 Meta */
.nav-folder-title[data-path^="000"] {
    color: var(--FoldText);
    background: var(--Fold0) !important;
    border-bottom: 2px solid var(--Fold0);
}

.nav-folder-title[data-path^="000"] + .nav-folder-children > .nav-file  {
background-color: var(--Fold0File);
}

.nav-folder-title[data-path^="000"],
.nav-folder-title[data-path^="000"] + .nav-folder-children,
.nav-file-title[data-path^="000"] {
    border-left: 2px solid var(--Fold0);
    margin-left: 3px;
    color: var(--FoldText);
}

(etc)
``

**Comment by AnubisNekhet** [comment]
Folder colors that aren't just a simple looping rainbow or set pattern are pretty tough to pull off since everyone has their own folder structure and unique names 😅. If there was an objective way to style specific stuff for everyone, I'd love to hear about it though.

**Comment by AnubisNekhet** [comment]
I'm considering making a repo for snippets/use the pre-existing snippets folder for fun little extra features like this though, though you'll need to have sass installed and know how it works :)

**Comment by brimwats** [comment]
maybe something like how supercharged links works? theirs looks like

```
div[data-id="ba98-dd7d"] div.setting-item-description::before,
.data-link-icon[data-link-ResearchType="Action&Method"  i]::before {
    content: var(--ba98-dd7d-before);
}
``` 

but it's set in the plugin settings. Maybe a css script or a stylesettings things that looks for a data-link in the field name?

**Comment by brimwats** [comment]
the field name for example being like a stylesettings option where the user enters part of a name of the folder they want

**Comment by AnubisNekhet** [comment]
Iirc css doesn't really support variables inside attribute selectors, so it's not really dynamic and can't be structured that way, sadly. I can make it semi-modular with scss though, in the sense that you need to edit a single file and then compile it to get a snippet.

**Comment by brimwats** [comment]
thats a great idea! wouldn't have thought of it

**Comment by AnubisNekhet** [comment]
Closing this issue since it is outside the scope of the theme, though it's on my priority and being worked upon in a separate snippet repo.
