### ISSUE TITLE
Chnage the color of the active menu [Feature Request] 

### ISSUE THREAD

**Issue by bassamsdata** [AnubisNekhet/AnuPpuccin#101]
First, congratulations on the voted Best Theme 2022 awards 🎉

**Feature Description**
Change the color of active menu option while navigating the menu to distinguish what is the active option inside the menu 
this is in light mode (Latte or rosé-pine). Video will explain it better.

**Miscellaneous Features**
This is even for the command menu (ctrl+p) or (ctrl+o)

**Additional context**
It's just to distinguish which option we are choosing from the menu, because the two colors are so similar. 
Well, I'm not sure if it just me or it's really hard to see which option I'm choosing.

Video: (in the video I'm navigating through arrow keys but I really don't see it, maybe just me 🫣)
thank you 

https://user-images.githubusercontent.com/105807570/221888033-d2badd79-f277-46e7-970b-59b4fb35978b.mov

**Comment by AnubisNekhet** [comment]
I noticed this issue with the card layout setting and I've fixed it, it should be available in the next release!

**Comment by bassamsdata** [comment]
Thank you for fixing that.

**Comment by AnubisNekhet** [comment]
Implemented with v1.4.0!
