### ISSUE TITLE
[Feature Request] Ideas about the workspace layout card view 

### ISSUE THREAD

**Issue by Harriet-Zhang** [AnubisNekhet/AnuPpuccin#102]
Hello, thank you very much for your beautiful theme, but I have an idea about the layout of the theme workspace. When the layout of the workspace is changed from the default to the card form, the solid line at the bottom of the title bar will become a dotted line, especially when the banner plug-in is used, the page does not look very integrated. Can you change this line to a solid line or add a button for custom configuration? Thank you.

<img width="700" alt="SCR-20230216-t50-2" src="https://user-images.githubusercontent.com/110753297/222022792-a1ab0638-84c1-4f98-a1a9-c3562a44cf74.png">

![SCR-20230216-tcc-2](https://user-images.githubusercontent.com/110753297/222022815-e95831e0-5c28-47ab-9f37-86f316c70a95.jpeg)

![SCR-20230216-tc3-2](https://user-images.githubusercontent.com/110753297/222022838-840ddab9-0ead-4f4c-ae6b-d8a7ea21b9f8.jpeg)

**Comment by AnubisNekhet** [comment]
Fixed with v1.4.0!
