### ISSUE TITLE
The border line seems not to be able to cancel in Card Layout

### ISSUE THREAD

**Issue by ProudBenzene** [AnubisNekhet/AnuPpuccin#107]
Hello!

Just like the picture, when I'm in the Light Mode of Card Layout, the card border lines are so obvious.

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/93238080/223593496-2c32a4b6-f52f-4add-ae18-a9eadde9d9bd.png">

Then I went back to V1.3 and found that it seems this option in Style Settings disappeared in V1.4.

<img width="738" alt="image" src="https://user-images.githubusercontent.com/93238080/223593614-7fbffe85-d26d-4934-9a3e-a9bad930037a.png">

Could you please add the option back? I need the I really need this beautification very much.

Thank you!

**Comment by ProudBenzene** [comment]
P.S. I am using the Solarized Extended Scheme, and it seems in other light schemes the border is not so obvious like this...

**Comment by AnubisNekhet** [comment]
I see, I'll bring it back then.

**Comment by AnubisNekhet** [comment]
Implemented with v1.4.1
