### ISSUE TITLE
[Feature Request] Add settings specifically for each of 4 direction of padding of callouts (and their titles)

### ISSUE THREAD

**Issue by HynDuf** [AnubisNekhet/AnuPpuccin#108]
**Feature Description**
I would like the settings specifically for each of 4 direction padding of callout's content and title. There is currently padding setting for all 4 direction.

**Additional context**
The motivations for this is:
- Make the title of callouts more aligned with the icon. Currently, the title seems to be "shifted up" a little bit (and make me uncomfortable)
![image](https://user-images.githubusercontent.com/29995756/223608598-05577c52-01c1-4299-908e-0754ff3b1d27.png)

- Left content padding were larger than top content padding in previous release (iirc). Content padding changed in the recent release made those 2 becomes the same leads to spacious look (if I were to increase the left padding to look like before), like below 
![image](https://user-images.githubusercontent.com/29995756/223610001-614d015f-a499-49e5-8251-82e7f10d57e7.png)
  
Thanks a lot.

**Comment by AnubisNekhet** [comment]
The easiest fix I can think of is changing the field to accept values along with their parameters so you could do something like `2px 0 0 2px`. Is that fine with you?

**Comment by HynDuf** [comment]
> The easiest fix I can think of is changing the field to accept values along with their parameters so you could do something like `2px 0 0 2px`. Is that fine with you?

Yes, totally. Thanks so much.

**Comment by AnubisNekhet** [comment]
Implemented with v1.4.1
