### ISSUE TITLE
Customizable link color

### ISSUE THREAD

**Issue by Missionary-OSBS** [AnubisNekhet/AnuPpuccin#109]
**Feature Description**
Internal link `[[ ]]` & External link (Markdown link) `[]()` have an option to edit color. 

**Alternative**
I use _Force Custom Accents_ to customize the link color but it also modifies other accent element color

**Comment by AnubisNekhet** [comment]
I'd suggest using a snippet to achieve that effect. I don't have any plans (at the moment) to add options to customize links since they add a lot of selectors, sorry 😅

**Comment by Missionary-OSBS** [comment]
`.cm-hmd-internal-link {
  color: green !important;
}`

I tried to add `.theme-light` / `.theme-dark` before `.cm-hmd-internal-link`but it doesn't work. How can I change colour based on dark / light mode ?

**Comment by AnubisNekhet** [comment]
Try this: `.cm-hmd-internal-link { --link-color: green; }` for source mode and `.internal-link { --link-color: green; }` for live preview and reading mode.

**Comment by Missionary-OSBS** [comment]
But what I mean is the link color should be different between light & dark mode. 
E.g. In light mode `.theme-light.cm-hmd-internal-link { color: green; }` , the link color is green. But in dark mode `.theme-dark.cm-hmd-internal-link { color: blue; }`, the link color is blue. 
And it does not work.

**Comment by papatistos** [comment]
> Try this: .cm-hmd-internal-link { --link-color: green; } for source mode and .internal-link { --link-color: green; } for live preview and reading mode.

So this means there is no theme setting that allows me to adjust the link colour independently of the accent colour, right?  Maybe it's just me, but I don't see why the link colour should be the same as the accent colour. It would be great if you could consider a setting for the link colour, perhaps under "File Editor and Markdown Elements".
