### ISSUE TITLE
[Feature Request] add border Line after the Headings Option

### ISSUE THREAD

**Issue by vkbytes** [AnubisNekhet/AnuPpuccin#11]
The Minimal theme has this option of adding the Below boarder line for headings which looks like an underline, This options for headers seem to be quite ascetically pleasing. If this can be added to Anuppuccin it would be great

![CleanShot 2022-10-31 at 22 09 17](https://user-images.githubusercontent.com/79217316/199061970-66b9115e-dedb-4613-82ca-e0fa73dcc7d0.png)

**Comment by AnubisNekhet** [comment]
Implemented with v1.1.7
