### ISSUE TITLE
[Feature Request] Codeblock: language and numbered lines visible in reading view

### ISSUE THREAD

**Issue by reouvenzana** [AnubisNekhet/AnuPpuccin#110]
Hello and thanks for this beautiful theme.

Shouldn't the codeblocks display the language and the line numbers as well in the reading view?

Thanks!

**Comment by AnubisNekhet** [comment]
Line numbers are not possible with CSS alone in reading view since there are no property values to indicate the position of the current line. I'd suggest using https://github.com/stargrey/obsidian-better-codeblock to achieve the same in reading view.
