### ISSUE TITLE
[Feature Request] Instructions for how to change settings

### ISSUE THREAD

**Issue by digitalsignalperson** [AnubisNekhet/AnuPpuccin#112]
**Feature Description**
I could use help with basic instructions for how to change settings

e.g. "The theme supports various palettes (5.." - how do I pick one?

Am I supposed to edit .scss files and then rebuild with sass? Or am I missing somewhere that there is a menu/UI to edit all the parameters? I have a feeling it's super easy and I'm completely missing something

**Additional context**

I'm new to using Obsidian themes other than the default one. I saw this won the best theme of 2022 so I wanted to try it. Here's how I ended up here:

- Installing from within Obsidian, I noticed I didn't find any settings within obsidian to access the different features.
- I found the theme folder and opened the css file to see if I'm supposed to toggle stuff in there and noticed the interesting settings markup... 
- So then I went to the github page, followed the instructions to clone it, then `sass src/base.scss theme.css`

so I gather maybe I'm supposed to edit individual .scss files? I'm not sure. I think I'm missing something obvious. Like something tells me there is a UI somewhere to pick options.

**Comment by trainbuffer** [comment]
In the first paragraph here -> https://github.com/AnubisNekhet/AnuPpuccin

>This theme makes heavy use of the [style settings](https://github.com/mgmeyers/obsidian-style-settings) plugin, which controls most of the features in the theme. The theme is perfectly usable even without style settings, but it's only a fraction of what it actually is with the plugin.

Further down:

>The theme supports various palettes (5 in the base theme and even more if you use the [extended colorschemes](https://github.com/AnubisNekhet/AnuPpuccin/blob/main/snippets/extended-colorschemes.css) snippet...

The Style Settings community plugin (and the extended colorschemes snippet if you want it) are where the theme options are.

**Comment by digitalsignalperson** [comment]
Ah thank you. Sorry I missed that. My only suggestion would be to add "install style settings plugin" or "requirements" in the installation section of the readme (for me that's what I immediately jumped to).
