### ISSUE TITLE
[Bug] Card Workspace Background not consistent when put into background 

### ISSUE THREAD

**Issue by Nova38** [AnubisNekhet/AnuPpuccin#113]
**Describe the bug**
When the user set the workspace mode to be card mode and then unfocused the window there are some unexpected changes to the ui. Namely two things: 

1. When the windows is focused the actions bar shares the same background as the file browser, however when not focused the background of the file browser dims like the rest of the background but the actions bar does not create a hard transition that messes with the clean look of the card mode.
2. if a second right sidebar is open when it is focused it has the same background as the rest of the sections, however when the windows is unfocused it has a box around it that has the undimmed background color.

**To Reproduce**
1. Go to style settings ->Workspace -> workspace layout -> change workspace layout variant to cards.
2. Then open up the left side bar and drag one of the tabs down so that it is split 
3. Unfocus the window.

**Expected behavior**
The background of the actions bar and the second right side bar should dim so that all of the background elements remain the same.

**Screenshots**
The are two sets of screenshots each with some of the different sections card format enabled. The first of each show the window focus and the second shows the window unfocused.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/17151865/223937260-26b5e46c-c72f-419e-9d65-6c339949519c.png">

<img width="700" alt="image" src="https://user-images.githubusercontent.com/17151865/223937347-8cd349a3-5a2b-4f2a-a072-2a88e0ae13e6.png">

<img width="700" alt="image" src="https://user-images.githubusercontent.com/17151865/223938997-4a0a5360-d7c5-484b-ab38-9aa47a352fa3.png">

<img width="700" alt="image" src="https://user-images.githubusercontent.com/17151865/223938976-ff4b0d6c-d34d-4186-8232-6ed44121c813.png">

**Additional context**

**Comment by AnubisNekhet** [comment]
Fixed with v1.4.1
