### ISSUE TITLE
[Bug] Colorful tags doesn't work under callout

### ISSUE THREAD

**Issue by pgyogesh** [AnubisNekhet/AnuPpuccin#114]
**Describe the bug**
Colorful tags don't work under callout if added in list

**To Reproduce**
1. Create tags under callout in list

**Expected behavior**
tags should be colorful under callout
**Screenshots**

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/18283952/224245591-2e514ca2-732b-470d-b702-9c8f00b0b1c5.png">

**Comment by AnubisNekhet** [comment]
This is an issue caused by the snippet, I'd suggest raising an issue on the snippet's repo.
