### ISSUE TITLE
[Feature Request] Add an option to choose new tab button side

### ISSUE THREAD

**Issue by sundevista** [AnubisNekhet/AnuPpuccin#119]
**Feature Description**
I like when new tab button placed near last tab, such as the one in default theme. So I guess the option to choose a side would be nice to have.

![image](https://user-images.githubusercontent.com/56955307/224551232-19c8f058-ad7f-46f3-b41a-821026447328.png)

**Miscellaneous Features**
Additional features that may be implemented in the feature but are not necessary per se

**Additional context**

**Comment by AnubisNekhet** [comment]
![image](https://user-images.githubusercontent.com/102488279/225013201-60dcd731-ac14-4aab-934a-bded3f66edac.png)
