### ISSUE TITLE
[Feedback Needed] Kanban styling

### ISSUE THREAD

**Issue by pryley** [AnubisNekhet/AnuPpuccin#12]
@AnubisNekhet 

These are suggested tweaks for Kanban boards from my CSS Snippets. I have added checkboxes to each suggestion, so feel free to tick the ones you like (if any).

### Details

- [x] 1. Grid background similar to Canvas except with 10px gap between dots instead of 20px gap (because the Kanban columns have a 10px gap).
- [ ] 2. Hide the "More options" button on cards (because you can right-click a card for the same menu).
- [x] 3. Highlight cards on hover
- [x] 4. Dim the text of completed cards to make them visually appear more inactive.
- [ ] 5. Reduce the border-radius of cards to better suit the small gap between cards (or perhaps remove the radius altogether?)
- [ ] 6. Remove the border radius of checkboxes in cards (it matches the cards better when the card radius is smaller)
- [x] 7. Remove the accent colour from tags (the background colour makes them look like buttons so they don't need a colour to make them look clickable; also, removing the accent colour make them less visually prominent).
- [ ] 8. Move the "Archive card" button to the right of completed cards, and only display it on hover.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/134939/210186334-88c428e7-fc76-4f1c-be2b-cedf7260c160.png">

### Before

![Screenshot 1](https://user-images.githubusercontent.com/134939/210186160-9a957712-1fca-462d-a512-ed99f96effdc.png)

## After

![Screenshot 2](https://user-images.githubusercontent.com/134939/210186546-0fc99370-ccd0-4059-bde8-e8fa95055148.png)

**Comment by AnubisNekhet** [comment]
Thank you so much for contributing so much to this theme, it means a lot to me 😊
I love your tweaks, especially the canvas-like background. I've added some notes to the boxes I didn't tick, just for some clarification:
2: I'd prefer keeping that menu button even though it's just a waste of space because I want to keep the theme accessible and approachable.
5, 6: I'd like keeping it as vanilla as possible since I presume a lot of people who want a custom radius would have a snippet already.
8: Same reason as 8 😅

**Comment by pryley** [comment]
Okay, that's fine. What about a slight modification to the grip icon and lane buttons?

I see that you have changed the lane buttons to dark on hover (instead of light on hover like other buttons) and added a dark background to the grip icon. I'm guessing you changed the background of the grip icon because it was too similar to the menu button icons, and changed the hover background on the lane buttons to match the grip background?

Only thing is that it makes those buttons inconsistent with the rest of the buttons in the UI (i.e. card buttons).

Alternatively, you could dim the grip icon to better differentiate it from the menu icons. Then it could look like this: 

**Hover state of menu button:**
<img width="396" alt="image" src="https://user-images.githubusercontent.com/134939/210201344-c3eae940-650b-4fbb-b5f3-9d47de3aa010.png">

**Hover state of Add card button:**
<img width="378" alt="image" src="https://user-images.githubusercontent.com/134939/210201436-79871c3b-ae0a-432f-a5c7-00c209212d3a.png">

Thoughts?

**Comment by jairjacom** [comment]
You guys are awesome. Paul you're an angel.

**Comment by AnubisNekhet** [comment]
> Okay, that's fine. What about a slight modification to the grip icon and lane buttons?
> 
> I see that you have changed the lane buttons to dark on hover (instead of light on hover like other buttons) and added a dark background to the grip icon. I'm guessing you changed the background of the grip icon because it was too similar to the menu button icons, and changed the hover background on the lane buttons to match the grip background?
> 
> Only thing is that it makes those buttons inconsistent with the rest of the buttons in the UI (i.e. card buttons).
> 
> Alternatively, you could dim the grip icon to better differentiate it from the menu icons. Then it could look like this:
> 
> **Hover state of menu button:** <img alt="image" width="396" src="https://user-images.githubusercontent.com/134939/210201344-c3eae940-650b-4fbb-b5f3-9d47de3aa010.png">
> 
> **Hover state of Add card button:** <img alt="image" width="378" src="https://user-images.githubusercontent.com/134939/210201436-79871c3b-ae0a-432f-a5c7-00c209212d3a.png">
> 
> Thoughts?

This looks amazing 👍

**Comment by pryley** [comment]
> 2: I'd prefer keeping that menu button even though it's just a waste of space because I want to keep the theme accessible and approachable.

I have opened an Feature Request issue for this here: https://github.com/mgmeyers/obsidian-kanban/issues/715

**Comment by AnubisNekhet** [comment]
Implemented :)
