### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by whichy** [AnubisNekhet/AnuPpuccin#120]
**Describe the bug**
Card snippet doesn't work as expected

**To Reproduce**
1. I added the kepano snippet
2. I turned it on
3. Setup a test page with a dataview query
4. It isn't displaying as cards - but more like a differently formatted table

**Expected behavior**
I expected to get a card/boxed display

**Screenshots**
1. ![withsnippet](https://user-images.githubusercontent.com/838292/224856353-b307ff45-61d4-4186-a165-95e46410b39a.jpg)
2. ![withoutsnippet](https://user-images.githubusercontent.com/838292/224856354-288db81a-2d41-4eaa-8b76-f6a3104cf109.jpg)
3. ![using minimal](https://user-images.githubusercontent.com/838292/224856623-d8145773-1a59-4c1e-ab3e-67f1f8f08711.jpg)

**Additional context**
I switched to minimal theme and the display works as expected.  
I have three screenshots - 
1 - the page display with AnuPpuccin and the CSS for the cards
2 - the page display with AnuPpuccin with just a regular table output and no card css
3 - same page as screen 1 with the Minimal theme

**Comment by AnubisNekhet** [comment]
You probably did not compile the snippet, I recommend using [this compiled file](https://github.com/AnubisNekhet/AnuPpuccin/blob/main/snippets/minimal-cards.css).

**Comment by whichy** [comment]
no, this didn't help at all.  same exact results.  I also (just to be sure) when in and turned off the style settings table formatting to make sure it wasn't conflicting.
