### ISSUE TITLE
Rainbow Folders doesn't work in my vault

### ISSUE THREAD

**Issue by skeskali** [AnubisNekhet/AnuPpuccin#121]
I've tried uninstalling and reinstalling the theme, but no matter what I try I can't get rainbow folders to show in my vault. Do you know if AnuPpuccin's rainbow folders conflicts with any other Obsidian extensions? Thank you.

**Comment by AnubisNekhet** [comment]
Do you have the style settings plugin installed and have you enabled rainbow folders in the style settings section?

**Comment by skeskali** [comment]
Yes to both.

**Comment by syrth-io** [comment]
this kind of thing is tricky to solve without any additional detail, but a few things I can think of to check are:
- if you have the simple style enabled, that at least one toggle under the "Simple Folder settings" is on
- if you have any snippets enabled, toggle them on/off one at a time with rainbow folders on to see if anything changes
- if you have any appearance-altering plugins, try the same
- attempting to replicate this in the sandbox vault or a separate, fresh vault with nothing but the theme and style settings installed
- that style settings and the theme are both up-to-date
- that obsidian and/or your installer are up-to-date
- that the base rainbow folder functionality and optional customization snippet aren't being confused with one another (which would include a few more things to check that don't necessarily apply to the base functionality)

a lot of that probably seems obvious or may be something you've already tried, but I often find myself forgetting to try the most basic of troubleshooting tasks myself a lot.

**Comment by Origami74** [comment]
I had this same issue. I found that the `MAKE.md` plugin was the culprit. Disabling the `Spaces` feature of that plugin fixed the rainbow folders. I had both plugins enabled before and work well together, probably an update on either one of these plugins broke it.

**Comment by skeskali** [comment]
I thought it might've been Make.md, so I uninstalled it first. I still don't have rainbow folders.

**Comment by skeskali** [comment]
I think I found the answer. It's the File Tree Alternative Plugin. I made a new vault and started copying files over. Once I added the File Tree Alternative Plugin and enabled it, I lost Rainbow Folders. Disabling/uninstalling File Tree Alternative in the new vault did not bring rainbow folders back.

**Comment by AnubisNekhet** [comment]
I could not reproduce this issue. File Tree Alternative Plugin is not supported as of now, however I am welcome to PRs.
