### ISSUE TITLE
[Feature Request] The demonstration effect of embedding internal page in the form of ![[]]

### ISSUE THREAD

**Issue by Harriet-Zhang** [AnubisNekhet/AnuPpuccin#123]
Hello, I embed internal page in the form of ![[]] on the homepage, and the block lines on the left will appear in this way. Is it possible to add a function button similar to the minimal theme to achieve the effect of hiding lines and make the whole page look like more integrated?Thanks.

<img width="943" alt="SCR-20230316-oplq" src="https://user-images.githubusercontent.com/110753297/225562772-3b38addb-ea14-4465-bf0b-02c429f098ca.png">
<img width="792" alt="SCR-20230316-omnr" src="https://user-images.githubusercontent.com/110753297/225562795-214fdce3-fa1e-432a-9822-95d4ce721297.png">
<img width="823" alt="SCR-20230316-oqgt" src="https://user-images.githubusercontent.com/110753297/225562804-5f93cfc3-69b4-4614-ad23-f143781bf112.png">

**Comment by AnubisNekhet** [comment]
I believe ![[note|seamless]] should achieve the look you want.
