### ISSUE TITLE
[Bug]  Theme doesn’t allow paste the copied table on dataview to excel, It pasted plain text

### ISSUE THREAD

**Issue by ertugruluyar-github** [AnubisNekhet/AnuPpuccin#127]
**Describe the bug**
I copied a table from dataview’s table, then I pasted it to excel and it paste content as a plain text.
Things, Blue Topaz and Cybtron themes have same issue. If ı don't do the step 3 then I got the table, for this themes. But Default Obsidian theme still have the issue. However, when, in excel, I right clicked and select the paste special option, then select the unicode type, so problem gone.
Minimal Theme are allowing that. When ı pasted the content, excel got the table.

**To Reproduce**
1. Copy Dataview table
2. Open a Microsoft excel sheet.
3. Select all cell and set cell type to text from general. 
4. Paste the copied table

**Expected behavior**
An excel table.

**Screenshots**

**Additional context**

**Comment by ertugruluyar-github** [comment]
This issue happen my mouse way far down on screen when ı selecting the table. If ı select the exact table, which means my mouse don't way far down on screen when ı select the table, excel got the table. 
I think Minimal theme, even if, my mouse way far down when ı selecting the table, selecting only table.

**Comment by ertugruluyar-github** [comment]
This issue happen my mouse way far down on screen when ı selecting the table. If ı select the exact table, which means my mouse don't way far down on screen when ı select the table, excel got the table. 
I think Minimal theme, even if, my mouse way far down when ı selecting the table, selecting only table.

**Comment by AnubisNekhet** [comment]
If your issue still persists on the default theme, I'd recommend raising an issue there. AnuPpuccin does not make drastic changes to how tables work, i.e. it's essentially vanilla.
