### ISSUE TITLE
[Bug] theme callouts

### ISSUE THREAD

**Issue by aidalourandes** [AnubisNekhet/AnuPpuccin#129]
I can't use the theme callouts.

For some reason, the theme callouts are impossible for me to use. I can see there are some, like the capacities callouts and the multi-column callout, but when I try to use it, they are like a normal callout. 

I instaled the callout menager to see if I could use it that way, but it didn't help. The capacities options doesn't even appear to me when I start a callout in my text.  

I think something is missing in the callout options in the syle plugin, or something in the theme itself...

**Comment by syrth-io** [comment]
multi-column and capacities aren't native callouts or part of the theme; they're used with the CSS snippets [modular css layout](https://github.com/efemkay/obsidian-modular-css-layout) and capacities [cards](https://gist.github.com/AnubisNekhet/fdad92710522aa8968314b32e17d8d08) and [sidebar](https://gist.github.com/AnubisNekhet/33ceb77eb450d78b2833e77cdb8e3394) (the latter two also by the theme creator!).

at least, that's where I know them from - I'm not sure if there are other snippets using similar/same callout names.

**Comment by pryley** [comment]
Callouts work just fine. If you are using any custom CSS snippets, try disabling them to see if the fault is on your end.

You can test them by pasting the following in a new document:

```md
> [!note]+
> Here's a callout block.

> [!summary]+
> Here's a callout block.

> [!info]+
> Here's a callout block.

> [!tip]+
> Here's a callout block.

> [!done]+
> Here's a callout block.

> [!faq]+
> Here's a callout block.

> [!caution]+
> Here's a callout block.

> [!failure]+
> Here's a callout block.

> [!error]+
> Here's a callout block.

> [!bug]+
> Here's a callout block.

> [!example]+
> Here's a callout block.

> [!quote]+
> Here's a callout block.

> [!question] Can callouts be nested?
> > [!todo] Yes!, they can.
> > > [!example]  You can even use multiple layers of nesting.
```

<img width="624" alt="image" src="https://user-images.githubusercontent.com/134939/226777304-6eab6aed-7eea-479e-bdb9-0cd65fbc74c5.png">

**Comment by AnubisNekhet** [comment]
Closed due to inactivity
