### ISSUE TITLE
Great decision

### ISSUE THREAD

**Issue by DutchPete** [AnubisNekhet/AnuPpuccin#13]
Well done, Anubis, to resubmit your theme that so many people love.

As for accusations, bear in mind that the onus is on the accuser to prove their accusation. The onus is NOT on you to prove you did not violate anything. If anyone has the gall to accuse you, just answer “prove it”.

**Comment by AnubisNekhet** [comment]
Thank you so much!
I was kind of scared of putting this back up again, but I think I'd like my theme to be a bit easier to update and use for the people who still use it despite the rough patches it had. 😊
