### ISSUE TITLE
[Bug] Dark mode: th alternative-row does not work

### ISSUE THREAD

**Issue by emisjerry** [AnubisNekhet/AnuPpuccin#13]
Dark mode noes not have alternative-row effetc.

- Light mode is ok
![image](https://user-images.githubusercontent.com/131511/199184295-0571bf57-d31b-42c2-b781-52824fa78204.png)

- Dark mode noes not have alternative-row effetc
![image](https://user-images.githubusercontent.com/131511/199184344-04a0a3d7-cc74-4c45-910a-cd61fd59f71e.png)

**Comment by AnubisNekhet** [comment]
It does work, but it's really subtle in the colorscheme you've chosen.
I'll add a slider in the next update which allows you to set the darkness though.
