### ISSUE TITLE
Status bar gets in the way of other pane

### ISSUE THREAD

**Issue by Missionary-OSBS** [AnubisNekhet/AnuPpuccin#130]
**Feature Description**
In AnuPpuccin theme, the status bar covers a bottom section of a pane. Whereas, in ITS theme, I can customize it. 

- ITS theme
![2023-03-24_14 12 30_CSX](https://user-images.githubusercontent.com/98799613/227643234-101ab9a3-e67c-45ae-90c8-1235427ada85.jpg)

I can go to Style Setting and edit to raise the right sidebar
![2023-03-24_14 18 36_CSX](https://user-images.githubusercontent.com/98799613/227643556-f20e8a1d-524e-4415-bb44-e56e4543909e.jpg)

- AnuPpuccin theme: Currently there is no option for me to raise the right sidebar
![2023-03-24_14 12 49_CSX](https://user-images.githubusercontent.com/98799613/227643186-148d4ade-eeaa-483c-96ca-01b0ac01984a.jpg)

**Comment by AnubisNekhet** [comment]
<img width="701" alt="image" src="https://user-images.githubusercontent.com/102488279/227715897-a3e9b800-107d-4db2-84cc-da7d50633f4f.png">

**Comment by Missionary-OSBS** [comment]
I believe I saw that before but it always stays hidden unless I move the cursor to the corner of the screen. I prefer the option to make the Status Bar always visible but does not cover the right sidebar.

**Comment by AnubisNekhet** [comment]
I've added an option to make the status bar not float above other panels, it should be available with the next release.

**Comment by AnubisNekhet** [comment]
Implemented with v1.4.1
