### ISSUE TITLE
[Feature Removal]

### ISSUE THREAD

**Issue by YIRU69** [AnubisNekhet/AnuPpuccin#131]
**Feature to be removed**
![image](https://user-images.githubusercontent.com/48148292/228158056-ac2e6b58-2e6a-4c1d-9bf6-cd37ff04802f.png)

**Reason for removal**
Regarding the PDF file that is printed out, your theme is forcing it to output the corresponding background color directly on top of it. The only way to change this approach is to remove the code from your theme. I tried to remove the background using !important elsewhere, but failed.
**Additional context**
As a theme, I believe many others feel the same way - that we do not want to be restricted from exporting PDFs in our desired style. If I do not bring up this request, it would mean that every time you update, I would have to make changes again. I hope that you can remove this code or create a function that allows us to customize the PDF style. Thank you very much.

**Comment by AnubisNekhet** [comment]
A toggle for print styling has been implemented with v1.4.1

**Comment by YIRU69** [comment]
I really appreciate it.
