### ISSUE TITLE
[Bug] Recent File Plugin

### ISSUE THREAD

**Issue by avnibilgin** [AnubisNekhet/AnuPpuccin#132]
Info for Developer:

If you use the Obsidian "Recent File" Plugin, you can only open the recent files if you click exactly on the link text. A few millimeters to the right of the text, the left link is not recognized. Solution to the problem: go to the plugin style "Settings/AnuPpuccin/Workspace/File Browser/Fale lable alignment" and set it on  "right". It took me a few hours to figure that out. It would be nice if they pointed this out in some way.

**Comment by AnubisNekhet** [comment]
FIxed with v1.4.1
