### ISSUE TITLE
[Feature Request] Distinguish external/internal link

### ISSUE THREAD

**Issue by emisjerry** [AnubisNekhet/AnuPpuccin#133]
There's no way to distinguish external link or internal link.

Here's the fragment from Minimal theme:

```
<span class="cm-formatting cm-formatting-link-string cm-list-1 cm-string cm-url external-link" contenteditable="false"></span>
```

But external-link cannot be found now. Please add this class into cm-link. Thnaks.

**Comment by AnubisNekhet** [comment]
External links have an underline decoration while internal links do not have an underline. Unresolved links are dimmed for further recognizability. I'd recommend using a snippet to customize links as per your liking.
<img width="195" alt="image" src="https://user-images.githubusercontent.com/102488279/228769150-404e5ffd-f725-4c0f-8d75-210b69933f8e.png">
<img width="266" alt="image" src="https://user-images.githubusercontent.com/102488279/228769244-e7536c68-58bd-4363-8e9b-f1cd4a4a0291.png">

**Comment by papatistos** [comment]
A switch to let users decide whether internal or external links should be underlined would be nice. (To me, underlining external links makes more sense, so I will try to figure out how to achieve that, but if you could add a switch for that in the style settings, that would be great.)

Thanks for an awesome theme!
