### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ZeroKun265** [AnubisNekhet/AnuPpuccin#135]
**Describe the bug**
Custom checkboxes are visible in edit mode but not when printing or in view mode (even with print styling enabled)
**To Reproduce**
1. Add a bunch of custom checkboxes
2. try to go in edit mode (Ctrl+E) or export as pdf
3. Scroll down to see they show up as regular checkmarks

**Expected behavior**
They should have the same icons they have in edit mode
**Screenshots**
In edit mode:
![image](https://user-images.githubusercontent.com/64660715/228764197-b17d5001-dbbd-4d13-82c0-65ec925b6506.png)

In view mode:
![image](https://user-images.githubusercontent.com/64660715/228764596-84e257de-e7bb-4f43-b145-c53a4b0ed5b4.png)

**Additional context**
Custom speech bubbles seem to work, but not checkboxes

**Comment by AnubisNekhet** [comment]
I cannot seem to reproduce your issue. Have you tried updating the the latest Github version?

**Comment by ZeroKun265** [comment]
I downloaded it today from Obsidian itself, and over there it says version 1.4.0 which seems to be the newest one.
All I did was click install on Obsidian themes.

But i fixed it now, i downloaded from GitHub instead and then ran sass, now it works haha
(While I'm here is there a way to make the equivalent of the big quote but to close a sentence? I can't seem to find it)

**Comment by AnubisNekhet** [comment]
I don't think that's particularly possible with CSS alone, I'm afraid.
