### ISSUE TITLE
[Feature Request] Command Palette selection contrast improvement on amoled theme

### ISSUE THREAD

**Issue by sm-alejandro** [AnubisNekhet/AnuPpuccin#137]
**Feature Description**
The selection of an item is not clear (at least for me) in the command palette because it is too dark. The best solution for my case was to change the css class `.is-selected` from --background-secondary to --background-modifier-hover.

**Additional context**
This issue is similar to #101 

Thank you for the amazing theme, loving it so far

**Comment by AnubisNekhet** [comment]
Hopefully fixed with the latest release

**Comment by sm-alejandro** [comment]
Yes, it's perfect now. Thank you!!
