### ISSUE TITLE
[Bug] Rainbow Colouring for Folder Icons broken in Obsdian 1.2.0+

### ISSUE THREAD

**Issue by dvdmtw98** [AnubisNekhet/AnuPpuccin#138]
**Describe the bug**
The rainbow colored folder feature is broken in the latest version of Obsidian (1.2.0). The color is being applied correctly to the text but the folder icons are not being colored.

**To Reproduce**
1. Go to Style Settings - Workspace - Rainbow Folders
2. Enable the settings shown in image below
3. Check the folder icons in the sidebar

<img src="https://user-images.githubusercontent.com/31100937/229263821-93496c73-e5b9-4c60-aae9-a38f59bf9c34.png" width="500">

**Expected behavior**
The folder icons should also inherit the rainbow colors that are getting applied to the text

**Screenshots**

![Sidebar Folders](https://user-images.githubusercontent.com/31100937/229263917-24af4696-d42d-4ca0-a7c7-72cd215dd5c7.png)

**Additional context**
In the Desktop Insiders channel on Discord it was noted that there where minor changes made to the API used for the sidebar this could be the reason why the coloring is not working properly. The Sidebar File Count plugin also broke with the 1.2.0 update but it was quickly fixed by the developer.

**Comment by AnubisNekhet** [comment]
I've already noticed the change and I've updated the theme to work with the new CSS. It should be available with the next update.

**Comment by AnubisNekhet** [comment]
Implemented with v1.4.1
