### ISSUE TITLE
[Feature Request] Consistency in para and li spacing between preview and reading modes

### ISSUE THREAD

**Issue by spiritualgeek** [AnubisNekhet/AnuPpuccin#14]
**Feature Description**
A solution for inconsistent paragraph and `<li>` spacing between reading, preview and source modes would be nice

This is even prevalent in the base Obsidian theme, so not something unique to AnuPpuccin

I would appreciate it if there was more consistency between preview and reading modes

Moreover, it would be wonderful if spacing could be exposed to the Style Settings plugin to enable a more custom choice in spacing 

**Miscellaneous Features**
Not applicable

**Additional context**
See attached screenshot to see reading and preview modes

PS: Glad this theme is back

<img width="1428" alt="2023-01-04_18-13-27" src="https://user-images.githubusercontent.com/53917562/210600706-dae7e095-bc3e-4c1e-92dd-e025c7b38a1f.png">

**Comment by AnubisNekhet** [comment]
I think a separate snippet would be more appropriate for something like this so you could apply it to the base theme as well, I can certainly look into it 😄

**Comment by spiritualgeek** [comment]
I've been trying to piece one together, but I've been pulling my hair out 😂

**Comment by spiritualgeek** [comment]
Closed
