### ISSUE TITLE
Safari-style (Animated) Tabs get center aligned

### ISSUE THREAD

**Issue by ProudBenzene** [AnubisNekhet/AnuPpuccin#141]
After updating the theme, after setting the tab style to Safari-style (Animated) Tabs, if only one tab is opened, the tab will be centered by default, instead of left as before.

<img width="814" alt="image" src="https://user-images.githubusercontent.com/93238080/230758703-2a99dd19-1f3d-499f-90d6-33208ec977e2.png">

**Comment by AnubisNekhet** [comment]
That is an intentional design choice. If you disable the new tab alignment, the tabs will be aligned on the left while leaving it enabled will center them. I cannot change this due to CSS limitations.

**Comment by ProudBenzene** [comment]
Forgive me if I didn't quite understand it🥲, but the gist is that there is no way to set him to align to the left, right?
