### ISSUE TITLE
[Bug/Feature Improvement] Cannot select text below speech bubble

### ISSUE THREAD

**Issue by vnana-git** [AnubisNekhet/AnuPpuccin#142]
Thank you for creating this theme. 
Really love the design on layout, the feature on color folders and the lovely speech bubble.

**Describe the bug**
Cannot select the text below the speech bubble, this only happens on the last speech bubble while we do not have enough \n.

**Video**

https://user-images.githubusercontent.com/28506374/231062890-2e29af36-dc8a-4d52-946c-e3b12fcb8526.mov

**Comment by AnubisNekhet** [comment]
Could you please send the raw markdown for this file?

**Comment by vnana-git** [comment]
Sure, here is the Markdown for this file
[Untitled 1.md](https://github.com/AnubisNekhet/AnuPpuccin/files/11211164/Untitled.1.md)

This note is from my testing vault, with 8 community plugins in total. 
p.s.This issue is 1st happen in my Main vault.

Device for reference: 
iMac 
Ventur13.0.1 
Core Intel i5

Thanks
