### ISSUE TITLE
[Feature Request]  Options for removing link underlines

### ISSUE THREAD

**Issue by NIL-zhuang** [AnubisNekhet/AnuPpuccin#145]
**Feature Description**
I want to remove the link underline, or just distinguish between internal & external links, I can't find how to set the link underlines.
<img width="865" alt="image" src="https://user-images.githubusercontent.com/46214362/231781653-f59a9b6e-af1e-4983-b3a9-833bd9737b28.png">

**Comment by AnubisNekhet** [comment]
Similar to #133 
Please read my response on that issue.
