### ISSUE TITLE
Safari-style Tab settings is empty

### ISSUE THREAD

**Issue by pryley** [AnubisNekhet/AnuPpuccin#15]
Would be nice to have additional Safari-style Tab settings such as alignment (left, center, right) and gap size (spacing between tabs). I can see that there is a "Safari-style Tab settings" section which is empty, so maybe it's already planned?

Here I have customised the tabs to display on the left with a smaller gap:

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/134939/199345542-a374216f-fdc2-464d-8bff-063472066e70.png">

---

And in case it's of interest, here are the tweaks I have applied to your theme:

[Obsidian: Kanban tweaks](https://gist.github.com/pryley/9b7e94e7396ab8605ee45cf0089a9887)
- Custom background (borrowed from [Shimmering Focus](https://github.com/chrisgrieser/shimmering-focus))
- Tweak Cards (padding, border on hover, remove unnecessary context-menu button, etc.)
- Tweak Tags
- Reposition archive button on completed cards
- Dim and strike-through completed cards
- Fix code blocks in cards
- Custom Tags

[Obsidian: Window tweaks](https://gist.github.com/pryley/b851170b3e8558a96b4fe2f672e2b6ad)
- Crisp text
- Remove theme accent from tabs
- Remove the left ribbon
- Remove the new tab button
- Change the alignment and gap between Safari-style tabs
- Auto-hide the document toolbar
- Increase the document title font size
- Increase the tab font size

**Comment by AnubisNekhet** [comment]
Yep, I've planned some extra parameters for tabs but I haven't gotten around to actually implementing them.
I really love your tweaks though, can I use some parts in the theme? I'll credit you obviously. They look really great 😊

**Comment by pryley** [comment]
> can I use some parts in the theme?

Absolutely!

**Comment by pryley** [comment]
A little off topic I know, but here's another little tweak to display code block line numbers in edit mode. [I originally contributed this](https://github.com/chrisgrieser/shimmering-focus/issues/146) for the Shimmering Focus theme.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/134939/199346779-62aee0ce-06c8-45e8-8042-06a2dc8db19c.png">

**Comment by AnubisNekhet** [comment]
That looks super neat :)
I was wondering how to implement it a while back but your design looks really gorgeous.

**Comment by pryley** [comment]
Quick note about hiding the Kanban card buttons: if you decide to use that tweak, you might want to only hide them on desktop and not mobile. I forgot about that.

**Comment by AnubisNekhet** [comment]
Updated with v1.1.9 :)
