### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 103sbavert** [AnubisNekhet/AnuPpuccin#152]
**Describe the bug**
The add button in the files tab in a folder note with MAKE.md has poor background to foreground contrast

**To Reproduce**
1. Enable MAKE.md
2. Click on a folder to open it's folder note
3. Select the files tab from the section right below the note title
4. See the button to add new note

**Expected behavior**
A button with good icon to background contrast appears

**Screenshots**
![image](https://user-images.githubusercontent.com/65838896/236407385-414d452b-9b93-408a-8e73-9e97e6075d8e.png)

**Comment by AnubisNekhet** [comment]
Seems to be a MAKE.md theming issue, I'll PR a fix to them instead.
