### ISSUE TITLE
Can't click left sidebar button anymore

### ISSUE THREAD

**Issue by dubefab** [AnubisNekhet/AnuPpuccin#158]
Works with any other theme. My keyboard shortcut works but not the button.
On Mac OS.

**Comment by AnubisNekhet** [comment]
1. Have you tried turning off all snippets?
2. Could you send your theme style settings config?

**Comment by dubefab** [comment]
1. The only snipper I have is for extended version of your themes.
2. {
  "catppuccin-theme-settings@@catppuccin-theme-dark": "ctp-mocha",
  "things-style@@mobile-black-background": true,
  "things-style@@default-font-color": false,
  "things-style@@active-line": true,
  "things-style@@text-highlight-bg-l": "#9EE6D7",
  "things-style@@text-highlight-bg-d": "#007159",
  "blue-topaz-theme@@transparent-setting-panel": false,
  "blue-topaz-theme@@color-scheme-options": "color-scheme-options-autumn-topaz",
  "blue-topaz-theme@@hide-vault-name": true,
  "obsidian-prism-theme@@color-schemes-dt": "pt-color-scheme-indigo-dt",
  "blue-topaz-theme@@font-family-change-to-default": false,
  "blue-topaz-theme@@line-height-main": 1.6,
  "blue-topaz-theme@@font-text-theme": "Bookerly,'Inter', 'Segoe UI','霞鹜文楷 GB', 'LXGW WenKai', 'Segoe UI Emoji',var(--font-default)",
  "deeper-work@@line-height": 1.5,
  "encore-settings@@encore-coloured-tooltip": true,
  "name": "obsidian-california-coast-theme",
  "version": "1.0.0",
  "main": "index.js",
  "repository": "git@github.com:mgmeyers/obsidian-california-coast-theme.git",
  "author": "mgmeyers <matthew.gregory.meyers@gmail.com>",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "dotenv": "^8.2.0",
    "gulp": "^4.0.2",
    "gulp-concat": "^2.6.1",
    "gulp-rename": "^2.0.0"
  },
  "scripts": {
    "build": "gulp css",
    "dev": "gulp css:watch"
  },
  "anuppuccin-theme-settings@@anuppuccin-theme-light": "ctp-latte",
  "anuppuccin-theme-settings@@anp-active-line": "anp-no-highlight",
  "anuppuccin-theme-settings@@anp-file-icons": true,
  "anuppuccin-theme-settings@@anp-floating-header": false,
  "anuppuccin-theme-settings@@anp-custom-vault-toggle": false,
  "anuppuccin-theme-settings@@anp-card-layout-actions": false,
  "anuppuccin-theme-settings@@anp-card-layout-filebrowser": false,
  "anuppuccin-theme-settings@@anuppuccin-theme-accents": "ctp-accent-yellow",
  "Border@@Ribbon-autohide": true,
  "Border@@colorful-folder": true,
  "Border@@CTA-BTN-disable": true,
  "Border@@outline-enhanced": true,
  "Border@@theme-light-style-select": "theme-light-background-default",
  "Border@@theme-dark-style-select": "theme-dark-background-darker",
  "Border@@line-active-bg-color": "line-active-bg-color-accent",
  "Border@@h1-divider-on": true,
  "Border@@h2-divider-on": true,
  "Border@@h3-divider-on": true,
  "Border@@h4-divider-on": true,
  "Border@@h5-divider-on": true,
  "Border@@h6-divider-on": true,
  "Border@@card-layout-pad-open": true,
  "Border@@colorful-checkbox": true,
  "Border@@inline-title-color-select": "inline-title-color-designated",
  "Border@@h1-color-select": "h1-color-designated",
  "Border@@h2-color-select": "h2-color-designated",
  "Border@@h3-color-select": "h3-color-designated",
  "Border@@h4-color-select": "h4-color-designated",
  "Border@@h5-color-select": "h5-color-designated",
  "Border@@h6-color-select": "h6-color-designated",
  "Border@@folder-font-bold": false,
  "ul-theme-settings@@ul-theme-light": "ul-lobstertime-lt",
  "ul-theme-settings@@ul-theme-dark": "ul-lyt-dt",
  "anuppuccin-theme-settings@@anuppuccin-accent-toggle": true,
  "anuppuccin-theme-settings@@anp-decoration-toggle": true,
  "anuppuccin-theme-settings@@anp-italic-custom": "anp-italic-green",
  "anuppuccin-theme-settings@@anp-alt-rainbow-style": "anp-full-rainbow-color-toggle",
  "anuppuccin-theme-settings@@anp-rainbow-file-toggle": false,
  "anuppuccin-theme-settings@@anp-header-color-toggle": true,
  "anuppuccin-theme-settings@@anp-header-margin-toggle": true,
  "anuppuccin-theme-settings@@anp-colorful-frame": false,
  "anuppuccin-theme-settings@@anp-colorful-frame-icon-toggle-light": false,
  "anuppuccin-theme-settings@@anp-colorful-frame-icon-toggle-dark": false,
  "anuppuccin-theme-settings@@anp-collapse-folders": true,
  "pln@@pln-hdcl": true,
  "pln@@pln-hi-line": false,
  "encore-settings@@theme-dark": "encore-theme-dark",
  "encore-settings@@theme-light": "encore-theme-light",
  "sanctum@@active-line-accent": "var(--background-hover)",
  "anuppuccin-theme-settings@@anp-toggle-preview": false,
  "anuppuccin-theme-settings@@anp-custom-checkboxes": true,
  "anuppuccin-theme-settings@@anp-autohide-titlebar": true,
  "anuppuccin-theme-settings@@anp-table-toggle": true,
  "anuppuccin-theme-settings@@anp-layout-select": "anp-card-layout",
  "anuppuccin-theme-settings@@anuppuccin-theme-dark": "ctp-mocha",
  "obsidian-prism-theme@@accent-style-dt": "pt-accent-style-borderandfilled-dt",
  "obsidian-prism-theme@@dark-accent-color-preset": "pt-accent-color-purple-dt",
  "shiba-theme-settings@@shiba-colors-theme-dark": "Lilac-dark",
  "shiba-theme-settings@@shiba-accent-style": true,
  "shiba-theme-settings@@shiba-accent-colors": "accent-sea",
  "shiba-theme-settings@@hide-vault-title": false,
  "shiba-theme-settings@@shib-custom-vault-folder-toggle": false,
  "shiba-theme-settings@@shiba-remove-file-icons": false,
  "shiba-theme-settings@@shiba-toggle-folder-icons": true,
  "shiba-theme-settings@@shiba-toggle-indent-colors": true,
  "shiba-theme-settings@@shiba-toggle-indent-colors-accent": true,
  "shiba-theme-settings@@folder-style-change-options-colorful": "shiba-color-folder-background",
  "shiba-theme-settings@@folder-style-change-options-colors-palette": "folder-colorful-one",
  "shiba-theme-settings@@shiba-colors-theme-light": "default-light-theme",
  "shiba-theme-settings@@link-underline-internal": false,
  "shiba-theme-settings@@shib-disable-borders": false,
  "shiba-theme-settings@@shib-card-shadows": true,
  "shiba-theme-settings@@shib-card-layout-fileexplorer": true,
  "shiba-theme-settings@@shib-card-layout-actions": true,
  "shiba-theme-settings@@shib-minimal-cards-style-select": "minimal-cards-style1",
  "shiba-theme-settings@@shib-h1-underline": true,
  "shiba-theme-settings@@h2-font": "Fraunces9ptSuperSoft-Black",
  "shiba-theme-settings@@shib-h2-underline": true,
  "shiba-theme-settings@@h3-font": "Fraunces9ptSuperSoft-Black",
  "shiba-theme-settings@@shib-h3-underline": true,
  "shiba-theme-settings@@h4-font": "Fraunces9ptSuperSoft-Black",
  "shiba-theme-settings@@shib-h4-underline": true,
  "shiba-theme-settings@@h5-font": "Fraunces9ptSuperSoft-Black",
  "shiba-theme-settings@@shib-h5-underline": true,
  "shiba-theme-settings@@h6-font": "Fraunces9ptSuperSoft-Black",
  "shiba-theme-settings@@shib-h6-underline": true,
  "shiba-theme-settings@@blockquote-style": "blockquote-style-default",
  "shiba-theme-settings@@shiba-alt-tab-style": "shib-default-tab",
  "o-theme-settings@@responsive-text": 1.1,
  "shiba-theme-settings@@shib-th-highlight": true,
  "shiba-theme-settings@@shib-hb-select": "shiba-hb-style",
  "shiba-theme-settings@@shib-transparent-setting-panel": false,
  "obsidian-prism-theme@@color-schemes-lt": "pt-color-scheme-pistachio-lt",
  "shiba-theme-settings@@shib-callout-toggle": true,
  "shiba-theme-settings@@shib-callout-color-toggle": false,
  "shiba-theme-settings@@shib-callout-select": "shib-callout-style-1",
  "anuppuccin-theme-settings@@anp-callout-select": "anp-callout-sleek",
  "ap-theme@@theme-dark": "a-theme-apatheia",
  "ap-theme@@glassMorphism": true,
  "ap-theme@@smoothIndent": true,
  "ap-theme@@Fade": false,
  "ap-theme@@Hover": false,
  "ap-theme@@inline-title-font": "Open Sans",
  "GS@@AT": "CS_RS",
  "CS_Ukiyo_Dark@@CS_U_D_font": "CS_U_D_F_Asap_Default",
  "HL@@HL-sidedock": "HL-sidedock-PH",
  "M@@mode-smooth": true,
  "M@@mode-deep-dive": true,
  "typomagical-colour@@theme-variant": "ficus-ruby",
  "mado-11@@theme-color": "theme-daisy-blue",
  "at-theme-settings@@at-colorful-headings": true,
  "anuppuccin-theme-settings@@ctp-custom-text@@light": "#000000",
  "anuppuccin-theme-settings@@anp-list-toggle": true,
  "anuppuccin-theme-settings@@anp-codeblock-numbers": false,
  "anuppuccin-theme-settings@@anp-color-transition-toggle": true,
  "anuppuccin-theme-settings@@anp-h1-divider": true,
  "anuppuccin-theme-settings@@anp-h2-divider": true,
  "anuppuccin-theme-settings@@anp-h3-divider": true,
  "anuppuccin-theme-settings@@anp-h4-divider": true,
  "anuppuccin-theme-settings@@anp-h5-divider": true,
  "anuppuccin-theme-settings@@anp-h6-divider": true,
  "anuppuccin-theme-settings@@anp-alt-tab-style": "anp-default-tab",
  "anuppuccin-theme-settings@@anp-depth-tab-text-invert": false,
  "anuppuccin-theme-settings@@anp-bg-fix": true,
  "anuppuccin-theme-settings@@anp-card-shadows": false,
  "anuppuccin-theme-settings@@anuppuccin-light-theme-accents": "ctp-accent-light-sapphire",
  "anuppuccin-theme-settings@@anp-tooltip-toggle": false,
  "shiba-theme-settings@@shiba-clutter-free-headings": true,
  "shiba-theme-settings@@shiba-remove-heading-indicator": false,
  "shiba-theme-settings@@text-normal@@light": "#000000",
  "shiba-theme-settings@@shib-callout-fold-position": true,
  "o-theme-settings@@o-color-accent": "o-blue",
  "o-theme-settings@@o-bar": false,
  "o-theme-settings@@o-faintselect": false,
  "o-theme-settings@@o-header-line-h1": true,
  "o-theme-settings@@o-header-line-accent": "var(--color-accent)",
  "o-theme-settings@@o-header-line-h2": true,
  "o-theme-settings@@o-header-line-h3": true,
  "o-theme-settings@@o-header-line-h4": true,
  "o-theme-settings@@o-header-line-h5": true,
  "o-theme-settings@@o-header-line-h6": true,
  "o-theme-settings@@o-header-size": "o-headings-dec",
  "o-theme-settings@@o-kanban-style": "o-kanban-border",
  "Components@@tab-autohide": false,
  "Components@@Ribbon-autohide": true,
  "Components@@colorful-folder": true,
  "Components@@outline-enhanced": true,
  "Editor@@line-active-bg-color": "line-active-bg-color-accent",
  "Editor@@h1-color-select": "h1-color-designated",
  "Editor@@inline-title-color-select": "inline-title-color-designated",
  "Editor@@h1-divider-on": true,
  "Editor@@h2-divider-on": true,
  "Editor@@h3-divider-on": true,
  "Editor@@h3-color-select": "h3-color-designated",
  "Editor@@h4-divider-on": true,
  "Editor@@h4-color-select": "h4-color-designated",
  "Editor@@h5-divider-on": true,
  "Editor@@h5-color-select": "h5-color-designated",
  "Editor@@h6-divider-on": true,
  "Editor@@h6-color-select": "h6-color-designated",
  "anuppuccin-theme-settings@@anp-hide-status-bar": false,
  "anuppuccin-theme-settings@@anp-toggle-scrollbars": false,
  "anuppuccin-theme-settings@@anp-toggle-metadata": false,
  "anuppuccin-theme-settings@@anp-cursor": "pointer",
  "shiba-theme-settings@@h1-size": 1.9,
  "shiba-theme-settings@@h1-font": "Fraunces9ptSuperSoft-Black",
  "anuppuccin-theme-settings-extended@@anp-theme-ext-light": true,
  "anuppuccin-theme-settings-extended@@anp-theme-ext-amoled": false,
  "anuppuccin-theme-settings-extended@@catppuccin-theme-extended": "ctp-notion-light",
  "anuppuccin-theme-settings-extended@@anp-theme-ext-dark": true,
  "anuppuccin-theme-settings-extended@@catppuccin-theme-dark-extended": "ctp-kanagawa-dark",
  "o-theme-settings@@o-theme-light": "ul-obplus-lt",
  "o-theme-settings@@o-theme-dark": "o-shark-d",
  "aura@@cpt-accent": "var(--cpt-yellow)",
  "aura@@aura-colorshemes-dark": "default",
  "Components@@status-bar-autohide": false,
  "Maple@@heading-level-enable": true,
  "Maple@@color-use-custom": true,
  "Maple@@titlebar-colorful": false,
  "Maple@@bg-enable": "bg-default",
  "Maple@@status-bar-style-center": false,
  "Maple@@tab-float": false,
  "Maple@@tab-show-close": "tab-show-close-all",
  "Maple@@tab-title-bar-round": false,
  "Maple@@tab-title-bar-shadow": true,
  "Maple@@status-bar-float": true,
  "Maple@@tab-title-bar-text": "tab-title-bar-text-hidden",
  "Maple@@message-tooltip-hide-arrow": false,
  "Maple@@modal-header": true,
  "Maple@@modal-blur": true,
  "Maple@@setting-group-title": true,
  "Maple@@setting-nav-decoration": true,
  "Maple@@modal-slider": true,
  "Maple@@modal-toggle": "modal-toggle-default",
  "Maple@@modal-animation": true,
  "Maple@@scrollbar-hover": "scrollbar-hover-accent",
  "Maple@@scrollbar-movein-animation-disable": false,
  "Maple@@scrollbar-gutter": "scrollbar-gutter-default",
  "Maple@@font-maple": false,
  "Maple@@link-hover-expand": true,
  "Maple@@link-click-to-edit-in-live-preview": false,
  "Maple@@heading-h1-center": false,
  "Maple@@heading-h1-underline": true,
  "Maple@@heading-h3-underline": true,
  "Maple@@heading-h4-underline": true,
  "Maple@@heading-h5-underline": true,
  "Maple@@heading-h6-underline": true,
  "Maple@@tag-colorful": true,
  "Maple@@heading-h2-underline": true,
  "Maple@@heading-underline-thin": false,
  "Maple@@setting-line-height": 1.5,
  "Editor@@zoom-off": false,
  "Maple@@color-active-light": "color-active-default-light",
  "Maple@@setting-accent-h-light": 145,
  "Maple@@setting-accent-s-light": 32,
  "Maple@@setting-accent-l-light": 58,
  "Maple@@dv-enable": true,
  "Maple@@heading-color-style": "heading-color-colorful",
  "Maple@@setting-accent-h-dark": 290,
  "Maple@@canvas-group-hide": true,
  "notation-2-theme@@notation-colors": true,
  "notation-2-theme@@heading-colors-bg": "headings-rainbow",
  "notation-2-theme@@heading-colors": "headings-rainbow-text",
  "notation-2-theme@@font-select": "default-sans",
  "notation-2-theme@@banner-type-select": "banner-default",
  "obsidian-joval-theme@@custom-max-line-width": 700,
  "obsidian-joval-theme@@text-align": "align-l",
  "obsidian-joval-theme@@switch-dcol": "col-mod-b",
  "Maple@@setting-h1-font": "lektorat",
  "Maple@@setting-h2-font": "lektorat",
  "Maple@@setting-h3-font": "lektorat",
  "Maple@@setting-h4-font": "lektorat",
  "Maple@@setting-h5-font": "lektorat",
  "Maple@@setting-h6-font": "lektorat",
  "polka@@ss-border-radius": 0.25,
  "maple-basic@@color-use-custom": true,
  "maple-basic@@setting-accent-h-light": 200,
  "maple-editor@@setting-line-height": 1.5,
  "maple-editor@@font-maple": false,
  "maple-workspace@@titlebar-colorful": true,
  "maple-workspace@@bg-enable": "bg-static",
  "maple-workspace@@tab-float": false,
  "maple-editor@@link-hover-expand": true,
  "maple-editor@@heading-level-enable": true,
  "maple-editor@@heading-h1-center": false,
  "maple-editor@@heading-h1-underline": true,
  "maple-editor@@heading-h3-underline": true,
  "maple-editor@@heading-h4-underline": true,
  "maple-editor@@heading-h5-underline": true,
  "maple-editor@@heading-h6-underline": true,
  "maple-editor@@line-indicator-disable": false,
  "maple-basic@@setting-accent-h-dark": 225,
  "big-and-bold-theme@@page-shadow": false,
  "big-and-bold-theme@@file-line-width": 750,
  "big-and-bold-theme@@highlight-active-line": true,
  "big-and-bold-theme@@ultra-focus": true,
  "big-and-bold-theme@@colored-headings": true,
  "big-and-bold-theme@@custom-line-height": 1.5,
  "chime-theme@@theme-settings": "theme-chinchilla",
  "o-theme-settings@@o-colorfo-headings": true,
  "o-theme-settings@@o-header1-override": true,
  "o-theme-settings@@o-header1-override-size": 2,
  "maple-workspace@@tab-title-bar-text": "tab-title-bar-text-hidden",
  "maple-plugin@@dv-enable": true,
  "maple-workspace@@explorer-hide-name": true,
  "maple-basic@@setting-animation-time": 200,
  "maple-editor@@tag-style": "tag-colorful",
  "minimal-advanced@@styled-scrollbars": true,
  "minimal-advanced@@cursor": "default",
  "minimal-style@@active-line-on": false,
  "minimal-style@@callouts-style": "callouts-outlined",
  "minimal-style@@h1-l": true,
  "minimal-style@@h2-l": true,
  "minimal-style@@h1-size": "1.35em",
  "minimal-style@@h2-size": "1.3em",
  "minimal-style@@h3-size": "1.25em",
  "minimal-style@@h3-l": true,
  "minimal-style@@h4-size": "1.2em",
  "minimal-style@@h4-l": true,
  "minimal-style@@h5-size": "1.15em",
  "minimal-style@@h5-l": true,
  "minimal-style@@h6-size": "1.13em",
  "minimal-style@@h6-l": true,
  "minimal-style@@h4-variant": "normal",
  "minimal-style@@h5-variant": "all-small-caps",
  "minimal-style@@h6-variant": "all-small-caps",
  "minimal-style@@checkbox-shape": "checkbox-square",
  "minimal-style@@tabs-style": "tabs-default",
  "minimal-style@@sidebar-tabs-style": "sidebar-tabs-default",
  "minimal-style@@file-header-justify": "center",
  "minimal-style@@window-title-off": false,
  "minimal-style@@minimal-strike-lists": true,
  "minimal-style@@callout-blend-mode": "var(--highlight-mix-blend-mode)",
  "minimal-mobile@@mobile-toolbar-off": true,
  "minimal-style@@sidebar-lines-off": false,
  "minimal-style@@bold-weight": 700,
  "minimal-style@@bold-color@@light": "#E22F19",
  "minimal-style@@italic-color@@light": "#005D83",
  "minimal-style@@tx1@@light": "#000000",
  "minimal-style@@row-hover": true,
  "minimal-style@@tag-border-width": "1px",
  "minimal-style@@tag-radius": "14px",
  "minimal-style@@italic-color@@dark": "#F19F93",
  "minimal-style@@bold-color@@dark": "#F19F93",
  "minimal-style@@base@@dark": "#000000",
  "minimal-style@@bg1@@dark": "#000000",
  "minimal-style@@tx1@@dark": "#70BDF0",
  "serenity-theme@@color-scheme-select": "theme-rose-pine",
  "serenity-theme@@contrast-dark": "high-contrast-dark",
  "serenity-theme@@colorful-headings-s": true,
  "anuppuccin-theme-settings@@anp-kanban-hide-card-border": false,
  "anuppuccin-theme-settings@@anp-highlight-custom": "anp-highlight-yellow",
  "anuppuccin-theme-settings@@h1-size": 1.15,
  "anuppuccin-theme-settings@@h2-size": 1.14,
  "anuppuccin-theme-settings@@h3-size": 1.13,
  "anuppuccin-theme-settings@@h4-size": 1.12,
  "anuppuccin-theme-settings@@h5-size": 1.11,
  "anuppuccin-theme-settings@@h6-size": 1.1,
  "anuppuccin-theme-settings@@h1-font": "rubik",
  "anuppuccin-theme-settings@@h2-font": "rubik",
  "anuppuccin-theme-settings@@h3-font": "rubik",
  "anuppuccin-theme-settings@@h4-font": "rubik",
  "anuppuccin-theme-settings@@h5-font": "rubik",
  "anuppuccin-theme-settings@@h6-font": "rubik",
  "anuppuccin-theme-settings@@anp-colorful-frame-opacity": 1,
  "anuppuccin-theme-settings@@anp-hide-borders": false,
  "anuppuccin-theme-settings@@anp-callout-color-toggle": false,
  "anuppuccin-theme-settings@@cards-border-width": "1px",
  "anuppuccin-theme-settings@@anp-border-padding": 20,
  "anuppuccin-theme-settings@@anp-border-radius": 16,
  "anuppuccin-theme-settings@@h3-line-height": 1.2,
  "anuppuccin-theme-settings@@h4-line-height": 1.2,
  "anuppuccin-theme-settings@@h5-line-height": 1.2,
  "anuppuccin-theme-settings@@h6-line-height": 1.2,
  "anuppuccin-theme-settings@@anp-simple-rainbow-title-toggle": false,
  "anuppuccin-theme-settings@@anp-simple-rainbow-icon-toggle": false,
  "anuppuccin-theme-settings@@anp-header-divider-color-toggle": true,
  "Components@@nav-header-autohide": true,
  "Components@@tab-title-bar-fixed": false,
  "Components@@file-icon-color-select": "file-icon-color-accent",
  "Plugin@@colorful-checkbox": true,
  "Appearance-dark@@theme-dark-style-select": "theme-dark-background-darker",
  "Appearance-dark@@accent-dark": "#c4a7e7",
  "Appearance-dark@@background-primary@@dark": "#1f1d2e",
  "Appearance-dark@@background-secondary@@dark": "#191724",
  "Appearance-dark@@text-normal@@dark": "#e0def4",
  "Appearance-dark@@text-muted@@dark": "#908caa",
  "Appearance-dark@@text-faint@@dark": "#6e6a86",
  "Appearance-dark@@card-layout-open-dark": true,
  "Appearance-dark@@accent-color-override-dark": true,
  "Editor@@h1-size": "1.3em",
  "Editor@@h2-size": "1.25em",
  "Editor@@h3-size": "1.2em",
  "Editor@@h4-size": "1.15em",
  "Editor@@h5-size": "1.1em",
  "Editor@@h6-size": "1.05em",
  "Editor@@h2-color-select": "h2-color-designated",
  "Appearance-dark@@mod-left-split-background-select-dark": "mod-left-split-background-secondary-dark",
  "Appearance-dark@@mod-root-split-background-select-dark": "mod-root-split-background-transparent-dark",
  "notation-2-theme@@wys": false,
  "light-and-bright-theme@@light-theme-settings": "theme-default",
  "CS_GB_Dark@@CS_GB_D_font": "CS_GB_D_F_Amiri_Fancy",
  "Editor@@seamless-embeds": false,
  "custom-diegoeis-obsidianotion@@width-body-content": 700,
  "custom-diegoeis-obsidianotion@@eis-small-pinned-tabs": false,
  "custom-diegoeis-obsidianotion@@eis-hide-ribbon": true,
  "custom-diegoeis-obsidianotion@@size-h1": 1.5,
  "custom-diegoeis-obsidianotion@@size-h2": 1.45,
  "custom-diegoeis-obsidianotion@@size-h3": 1.4,
  "custom-diegoeis-obsidianotion@@size-h4": 1.35,
  "custom-diegoeis-obsidianotion@@size-h5": 1.3,
  "custom-diegoeis-obsidianotion@@size-h6": 1.25,
  "custom-diegoeis-obsidianotion@@font-paragraph": 1.2,
  "custom-diegoeis-obsidianotion@@frontmatter-font-size": 0.75,
  "ul-theme-settings@@ul-color-accent": "ul-blue",
  "ul-theme-settings@@ul-list-distinct": false,
  "ul-theme-settings@@ul-work-border": false,
  "ul-theme-settings@@ul-resize-border": false,
  "ul-theme-settings@@ul-bar": false,
  "ul-theme-settings@@ul-tag-border": false,
  "ul-theme-settings@@ul-prompt-grad": false,
  "ul-theme-settings@@ul-background-gradient": false,
  "ul-theme-settings@@ul-square-tabs": false,
  "ul-theme-settings@@ul-radius": "0",
  "ul-theme-settings@@font-text-theme": "Uncut Sans",
  "ul-theme-settings@@font-title": "Getai",
  "ul-theme-settings@@ul-faintselect": false,
  "ul-theme-settings@@ul-header-size": "ul-headings-opn",
  "ul-theme-settings@@ul-header-line-h1": true,
  "ul-theme-settings@@ul-header-line-h2": true,
  "ul-theme-settings@@ul-header-line-h3": true,
  "ul-theme-settings@@ul-header-line-h4": true,
  "ul-theme-settings@@ul-header-line-h5": true,
  "ul-theme-settings@@ul-header-line-h6": true,
  "ul-theme-settings@@ul-header-line-accent": "var(--color-accent)",
  "ul-theme-settings@@grad": false,
  "ul-theme-settings@@ul-floating-ribbon": false,
  "ul-theme-settings@@ul-folders": "ul-folder-anu",
  "o-theme-settings@@o-border": "var(--solid-border)",
  "o-theme-settings@@s-ul-cards": true,
  "o-theme-settings@@s-header-lapel": true,
  "o-theme-settings@@o-folders": "ul-folder-anu",
  "o-theme-settings@@o-osxcode": false,
  "o-theme-settings@@o-notitle": true,
  "Appearance-light@@accent-light": "#D7827E",
  "Appearance-light@@background-tertiary@@light": "#F2E9E1",
  "Appearance-light@@background-primary@@light": "#FFFAF3",
  "Appearance-light@@background-secondary@@light": "#FAF4ED",
  "Appearance-light@@text-normal@@light": "#575279",
  "Appearance-light@@text-muted@@light": "#797593",
  "Appearance-light@@text-faint@@light": "#9893A5",
  "Appearance-light@@card-layout-open-light": true,
  "Appearance-light@@theme-light-style-select": "theme-light-background-adapt",
  "Appearance-light@@accent-color-override-light": true,
  "Editor@@line-height-customize": 1.5,
  "maple-workspace@@tab-title-bar-round": false,
  "maple-editor@@line-active-disable": false,
  "maple-editor@@setting-h1-size": 1.5,
  "maple-editor@@setting-h2-size": 1.4,
  "maple-editor@@setting-h3-size": 1.3,
  "maple-editor@@setting-h4-size": 1.2,
  "maple-editor@@setting-h5-size": 1.1,
  "maple-editor@@setting-h6-size": 1.1
}
