### ISSUE TITLE
[Feature request] add option to have the same behavior as minimal theme for the codeblock and callouts

### ISSUE THREAD

**Issue by Rhydderch** [AnubisNekhet/AnuPpuccin#16]
**Basic outline of the feature:**
- In the minimal theme, the codeblock is not surrounded by a border when hovering over it and the "</>" indicator is shown on the far left side. This makes it less intrusive and more immersive.

**Specific goals:**
- If you have a particular issue to solve using said feature, please mention it since it helps me understand and better implement said feature.

**Current behavior**
(you can't see my mouse but I am hovering over the button and callout)
<img width="552" alt="image" src="https://user-images.githubusercontent.com/3197629/199461808-486255da-90d9-4b06-8481-dea16a3199fb.png">
<img width="534" alt="image" src="https://user-images.githubusercontent.com/3197629/199462045-de5cb3aa-0c4e-498e-bc21-b6090ea4bcbe.png">

**desired behavior** (minimal theme)
<img width="454" alt="image" src="https://user-images.githubusercontent.com/3197629/199461907-d7f4f037-c4e0-4d0b-ab36-091e8979989c.png">
<img width="550" alt="image" src="https://user-images.githubusercontent.com/3197629/199461952-d375a438-9c3d-403d-bc83-7b77ab587f71.png">

**Comment by AnubisNekhet** [comment]
Seamless callouts and codeblocks then, I'll try to cook up something.
