### ISSUE TITLE
[Bug] Inconsistent text decorations and link colors in highlighted text (text surrounded by `==`)

### ISSUE THREAD

**Issue by PoQuatre** [AnubisNekhet/AnuPpuccin#162]
**Describe the bug**
When you use bold, italic, internal or external link inside highlighted text (text surrounded by `==`) their colors are inconsistent between editing mode and reading mode.

**To Reproduce**
1. Open a new note.
2. Insert the following:
```
==This is some highlighted text to show issues with the colors of **bold text**, *italic text*, [[Internal Link]] and [External Link](https://google.com)==
This is a sanity check to prove that the is no issues with the colors outside of highlighted text: **bold text**, *italic text*, [[Internal Link]] and [External Link](https://google.com)
```
3. You then need to create the note `Internal Link` because weirdly enough unresolved links is the only thing to have no inconsistencies.
4. Now you can switch between editing mode and reading mode to see the color inconsistencies.

**Expected behavior**
IMO the bold and italic text should keep their colors in reading mode and links should always be colored as links.
This could either be done by applying this to the default styles or by adding a toggle in the theme settings (probably in the `Text Decoration` section)

**Screenshots**
Here is the demo text in editing mode:
![Demo text in editing mode](https://github.com/AnubisNekhet/AnuPpuccin/assets/24886086/30d85ffd-a2ba-40ad-9fb2-4a35f4e4426f)

And here in reading mode:
![Demo text in reading mode](https://github.com/AnubisNekhet/AnuPpuccin/assets/24886086/2847b0a3-c399-48ad-a6b9-54f62f83c7f2)

**Additional context**
I originally wanted to fix this with a pull request but i saw the code below so I wasn't sure if this was intended or not.
https://github.com/AnubisNekhet/AnuPpuccin/blob/9a63dc1d0a8d3f6dd977a8fef24cc70bc710eafc/src/modules/Markdown-Elements/decorations.scss#L7-L13

If needed I would be happy to make the pull request, I just need a confirmation on what would be the expected behaviors in these situations.

**Comment by AnubisNekhet** [comment]
That is indeed a stylistic choice, however I think removing it would be a better idea for a more vanilla experience.
