### ISSUE TITLE
[Bug] Problem with Rainbow Folders: Colors Not Displaying Correctly

### ISSUE THREAD

**Issue by moonyuno** [AnubisNekhet/AnuPpuccin#165]
I attempted to set up rainbow folders, but it appears that some colors are not being applied correctly. For example, rosewater looks the same as flamingo. Mauve looks the same as pink. The only color that appears distinct is yellow.

<img width="811" alt="image" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/77012374/89d93955-86e5-4179-9768-ca803f221df2">
 you can see that I selected different colors, but the folder colors still appear the same.

**Comment by AnubisNekhet** [comment]
This is due to a lot of accents in Rose Pine Light being the same color, since I ported it over to the Catppuccin color format without any changes. However, I will be changing the accents to be distinct in the near future.
