### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by RedLilith** [AnubisNekhet/AnuPpuccin#169]
Sorry to bother you. I noticed inside of style setting you have an option to change the font. And it could just be me messing up the css since I'm still learning, but when I tried to add a custom font, it didn't change at all. I wasn't sure if there was a specific way to go about it for the theme?

Thanks in advance.

**Comment by AnubisNekhet** [comment]
Hi, I'd suggest checking the following:
1. The font is installed on your device. (Mobile phones have a limited amount of fonts which can be the issue)
2. The font name matches the name of the font installed.

If this does not work, I'd suggest trying putting quotes around the font name.

**Comment by RedLilith** [comment]
This is what I'm using right now. It is a font that I've installed and moved into the font folder on my computer, so I know that's not the issue, and even with the !important it's still being ignored. I know you're already busy with this theme and your own stuff, so I do appreciate you trying to help. I was able to successfully change the colors of my header and the color and gradient of my in-line, so I thought I'd be able to do this. 

```/* Set fonts for both Edit and Preview mode
.view-content {
  font-family: 'Boogaloo', cursive; !important;
}
*/

.markdown-source-view {
  font-family: font-family: 'Boogaloo', cursive; !important;
}

.markdown-preview-view {
  font-family: font-family: 'Boogaloo', cursive; !important;
}
```

**Comment by AnubisNekhet** [comment]
I think this is the problem:
```diff
- font-family: font-family: 'Boogaloo', cursive; !important;
+ font-family: 'Boogaloo', cursive; !important;
```

**Comment by RedLilith** [comment]
I'm a little disappointed in myself that I didn't notice I doubled the font-family. Thank you!
