### ISSUE TITLE
[Feature Request] Adjust line height and letter spacing

### ISSUE THREAD

**Issue by KiligFei** [AnubisNekhet/AnuPpuccin#173]
Feature Description

Hello,

I want to be able to adjust the line height and spacing of the page, not just the H tag

I'm not sure if this is a reasonable request, but it's exactly what I'm looking for.

Thank you

Additional context
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/69230517/46bb1f9d-9838-49b2-9fea-3310fda6c5f5)

**Comment by dhry** [comment]
Seconding this request.

**Comment by DudeThatsErin** [comment]
What do you mean by this? I don't understand.
