### ISSUE TITLE
[Bug]  Extended color scheme doesn't work

### ISSUE THREAD

**Issue by h259bws** [AnubisNekhet/AnuPpuccin#178]
**Describe the bug**
After installing the extended-colorschemes.css, I still don't see any of the extended color schemes (light or dark). I only see Latte and Rosé Pine for light themes and Frappe, Macchiato, Mocha, and Mocha Old for dark themes.

**To Reproduce**
1. Install and activate the Style Settings plugin.
2. Install and activate the AnuPpuccin theme.
3. Download the CSS from [https://github.com/AnubisNekhet/AnuPpuccin/blob/main/snippets/extended-colorschemes.css](https://github.com/AnubisNekhet/AnuPpuccin/blob/main/snippets/extended-colorschemes.css), put it in a CSS file in the snippet folder, and activate it in under Obsidian Settings
4. Go to Style Settings > AnnuPpuccin > Colors.
5. Drop down the option for both Light Theme Flavor and Dark Theme Flavor. The extended colors do not appear.

**Expected behavior**
Expect to see more color choices under Light Theme Flavor and Dark Theme Flavor

**Screenshots**
<img width="1081" alt="one" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/16826279/3557aec8-afc9-4c6c-952a-4b3607d20f46">
<img width="782" alt="two" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/16826279/32711dbb-78e3-4553-8b4f-b7620c068edc">
<img width="826" alt="three" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/16826279/c458db6f-4bf3-49b6-b4ba-fdfacba5a303">
<img width="836" alt="four" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/16826279/b58e66dd-0dd7-4c44-b758-50bc6acb93d8">
<img width="827" alt="five" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/16826279/446723f6-9454-4068-adda-577b293a75c6">

**Additional context**

**Comment by syrth-io** [comment]
the extended color schemes actually show up under a separate category in style settings! probably easy to miss if you have snippets between the two.

![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/112804375/00922d0d-0bb0-4d7d-9132-2370a91ef931)
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/112804375/0607f354-f4f1-4095-8cb6-8ce190279713)

**Comment by h259bws** [comment]
I don't see an AnnuPpuccin Themes Extended section under Style Settings. And I don't understand what you mean by 'probably easy to miss if you have snippets between the two.'   
<img width="737" alt="StyleSettings" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/16826279/0563e1f0-a0fe-4342-83bc-b1a9e5e01381">
<img width="781" alt="snippets" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/16826279/b5508c88-6d27-43cb-a994-932a61da340d">

**Comment by syrth-io** [comment]
the extended color schemes are not grouped under the heading _AnuPpuccin_, as you have open in your screen caps. it's an entirely different group in style settings called _AnuPpuccin Themes Extended_, as if it were an entirely different plugin or theme. in my main vault, I have one snippet with settings between the default AnuPpuccin settings and the extended color schemes settings:
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/112804375/5ff7dfb8-6cef-471e-9ba9-a55a9ee39eb0)

so what I meant was, if you have any other snippets with settings that show up between the two in style settings (or a lot before them, even), you may need to scroll down to see see the extended color schemes (the Capacities section for mine).

**Comment by h259bws** [comment]
I understand what you're saying, but I don't see "AnuPpuccin Themes Extended under the Style Settings settings.
<img width="737" alt="StyleSettings" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/16826279/5985cd0c-ce6b-43fc-aa5b-5bb80bf39e22">

**Comment by h259bws** [comment]
Sorry, I attached the wrong screenshot. Here is the right one:
<img width="802" alt="StyleSetting_Settings" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/16826279/d045c41b-bd03-4ae6-b754-161bbf714139">

**Comment by h259bws** [comment]
I figured it out. Somehow my CSS file got corrupted and wasn't being recognized. Thanks for your help and patience.

**Comment by seajaysec** [comment]
@h259bws I'm in the same boat as you were - how did you solve this?

edit: Nevermind, figured it out. For me it was enabling the CSS snippets under Appearance.

**Comment by h259bws** [comment]
For me, it turned out to be a corrupt CSS file.

But if that's not the case for you, make sure you've put the snippet in
your Snippets folder (as set on the Appearance settings screen), that
snippet is enabled, and you've clicked the "reload snippets" button to
ensure it is loaded. Lastly, on the Style Settings configuration screen,
the extended color settings are under "AnnuPpuccin Themes Extended" -- NOT
under "AnnuPpuccin".

Hope this helps!

**Comment by Posedge** [comment]
> edit: Nevermind, figured it out. For me it was enabling the CSS snippets under Appearance.

Same issue here. Took me longer than it should have to figure it out... You should add this to the installation step in the readme.
