### ISSUE TITLE
[Feature Req] Distinguish external/internal link also in edit mode

### ISSUE THREAD

**Issue by Karl-Bee** [AnubisNekhet/AnuPpuccin#182]
your theme is great, thank you for that!

however in edit mode I cannot distinguish between an internal and an external link.
I did look in all settings and cannot find where to set.
it is a similar issue as: https://github.com/AnubisNekhet/AnuPpuccin/issues/145
and an answer has been given in https://github.com/AnubisNekhet/AnuPpuccin/issues/133
which only seems to work in preview mode
however the differentiation doesn't show up in edit mode.

Could you please implement it in both preview and edit mode?
I do work in edit mode most of the time

Thank you very much.

**Comment by AnubisNekhet** [comment]
As far as I can tell, Obsidian simply cannot differentiate between unresolved and resolved links. However, I have implemented a fix for underlines in Live Preview mode which fixes internal links having underlines.

**Comment by chris-lesage** [comment]
Hi there, you can distinguish unresolved links. This is what I use to make them wavy-underlined and a complementary colour.

Got this from the forum I think, but adapted: https://forum.obsidian.md/t/how-can-i-make-unresolved-link-display-differently/45171/2

As opposed to that answer in #133 (which I'm not familiar with), my snippet below only works in Edit Mode. Not in Reading Mode. But there must be a class for both, I assume. (Also sorry if I misunderstood, and this wasn't what either of you were talking about!)

```
.markdown-source-view.mod-cm6 .is-unresolved {
    color: orange;
    font-style: italic;
    text-decoration-style: wavy;
    text-decoration-line: underline;
}   
```
