### ISSUE TITLE
Use local images for the background feature

### ISSUE THREAD

**Issue by legolasdimir** [AnubisNekhet/AnuPpuccin#184]
**Feature Description**
Make it so you can use local images for the background. This might be possible already but there's no documentation.

**Comment by AnubisNekhet** [comment]
Recent changes to Obsidian have removed loading of local files via CSS, hence this feature is not possible anymore, or I might not know about any method to load local files through CSS which works with the newer versions of Obsidian. I'd appreciate any help on this matter though!

**Comment by legolasdimir** [comment]
@AnubisNekhet 

FireisGood from the discord created this

https://github.com/FireIsGood/obsidian-everforest-enchanted/blob/main/custom_background_image.md

I'm not sure it will help you at all.
