### ISSUE TITLE
[Bug] Massive space before H4 heading

### ISSUE THREAD

**Issue by DrLeucine** [AnubisNekhet/AnuPpuccin#190]
**Describe the bug**

There's a massive space before H4 Heading. Is there a way to disable this?

<img width="190" alt="Screenshot 2023-07-17 at 08 07 26" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/17524568/f13d5585-cecb-49f3-8068-96b9092d626f">

**To Reproduce**
Create an H4 heading

**Expected behavior**
Normal spacing

**Screenshots**
<img width="190" alt="Screenshot 2023-07-17 at 08 07 26" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/17524568/f13d5585-cecb-49f3-8068-96b9092d626f">

**Additional context**

**Comment by AnubisNekhet** [comment]
Have you disabled `Typography > Headings > Enable Custom Heading Margin` in Style Settings? If not, that might be the issue. Save for that toggle, the theme does not change heading margins in any matter.

**Comment by DrLeucine** [comment]
Weird, it was off but turning it on and off fixed the issue! Thank you :)
