### ISSUE TITLE
[Bug] Link hover underline disappeared in last 24 hours?

### ISSUE THREAD

**Issue by ajh3** [AnubisNekhet/AnuPpuccin#195]
Up until this morning, my links in Source Mode / Editing View received an underline on mouse hover (the same way it works in the default Obsidian theme). When I opened Obsidian today, it was no longer happening.  

I have tried disabling all community plugins and snippets -- no difference. And I don't think I updated or changed anything in the last 24 hours.

When I change the theme back to Default, the link underlining works as expected.

I'm not very familiar with CSS, but the issue seems to be here:

```
.cm-hmd-internal-link {
    --link-decoration: none;
    --link-decoration-hover: none;
    --link-decoration-active: none;
}
```

`--link-decoration-hover: none;` is doing it.

I set up the following snippet, which restores functionality to how it worked until now.

```
.cm-hmd-internal-link {
    --link-decoration: none;
    --link-decoration-hover: underline;
    --link-decoration-active: none;
}
```

I think that's an official Obsidian class, so I am not quite sure what's going on. (but as mentioned, this is only happening in AnuPpuccin.) I am happy to follow any debug instructions or provide other info on request, just give me instructions.

**Comment by AnubisNekhet** [comment]
That is indeed an intentional change (Re: #182). To provide uniformity to how external and internal links, unresolved and resolved are rendered in preview and edit modes. I may include a toggle to enable/disable link styling in the future.
