### ISSUE TITLE
So this has been removed from the store for reusing code? Is there any way to keep it up to date?

### ISSUE THREAD

**Issue by firinael** [AnubisNekhet/AnuPpuccin#2]
As title states. Wanted to keep using an updated version of this despite the silly removal from the store.

Also I'm pretty sure you can just put it back up, 99% of people won't care if you use their code as long as it's credited in the code and README file.

**Comment by AnubisNekhet** [comment]
I haven't really reused any code, the issue and reason for me taking down my theme was using colorschemes without permissions, whatever that means. Either way, I don't intend to keep it on the theme store since I don't possess the commitment to look over every aspect of my theme.

**Comment by AnubisNekhet** [comment]
As for updating, there's instructions in the README.

**Comment by erileff** [comment]
> I haven't really reused any code, the issue and reason for me taking down my theme was using colorschemes without permissions, whatever that means. Either way, I don't intend to keep it on the theme store since I don't possess the commitment to look over every aspect of my theme.

Thanks so much for continuing to update this theme! The nonsense that happened sucks, but your theme is wonderful.
