### ISSUE TITLE
Top Buttons Get Washed Out

### ISSUE THREAD

**Issue by Nooby-001** [AnubisNekhet/AnuPpuccin#21]
When setting the colorful frame to a light color (light theme) the top obsidian buttons get washed out, the nigh theme is ok.
Using latest Obsidian version and latest theme version.
Screenshots:
https://imgur.com/a/kVW6Wpx

**Comment by AnubisNekhet** [comment]
I've added an option to toggle the icon colors from light to dark, which should come with the next release.

**Comment by Nooby-001** [comment]
Thank you!
