### ISSUE TITLE
I'm curious how to make the example image

### ISSUE THREAD

**Issue by calmwaves111** [AnubisNekhet/AnuPpuccin#210]
Hello, I found that all the text on the example image has become a horizontal line, I'm curious how to make
![](https://github.com/AnubisNekhet/AnuPpuccin/blob/main/assets/gh-layout-preview.webp)
Also thank you so much for making such a nice theme, it's very beautiful I love it

**Comment by AnubisNekhet** [comment]
Can you please provide an image to give further context?

**Comment by calmwaves111** [comment]
of course. like this picture
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/56907077/3aa39000-56bf-4079-92e0-acf493bdf190)

**Comment by AnubisNekhet** [comment]
Sure! That specific image is made using [this plugin](https://github.com/kurakart/garble-text) for hiding the text, and [style settings](https://github.com/mgmeyers/obsidian-style-settings) for customisation.
