### ISSUE TITLE
Option to change the icon/color of the custom vault title.

### ISSUE THREAD

**Issue by albertoloscerritos** [AnubisNekhet/AnuPpuccin#212]
I think it would be a cool feature.

![custom_vault_title](https://github.com/AnubisNekhet/AnuPpuccin/assets/16707033/b6d29a0d-610d-4993-946f-8bb5fe2065f1)

**Comment by AnubisNekhet** [comment]
Marking as unplanned since adding more color options will increase theme size and load.
