### ISSUE TITLE
[Bug] File Icon Misalignment 

### ISSUE THREAD

**Issue by RicaInWanderland** [AnubisNekhet/AnuPpuccin#215]
Hello!

Thank you for the amazing theme.

I have been playing with the snippets and i realized that there is a misalignment for the notes not within the folder (see attached image).

I have been looking for a solution to reach the ideal alignment for the past few hours to no avail.
Could this be a bug or an error that can be fixed through css editing?

![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/143214478/338fd1c4-3c29-40e6-93a3-5ad8a0c87ade)

Thank you in advance!

**Comment by AnubisNekhet** [comment]
Added an option to change file icon position in the following [commit](https://github.com/AnubisNekhet/AnuPpuccin/commit/91e8c73d4669a4b78c476d4ab1d14d1ba33d575d).

**Comment by julianjuko** [comment]
Thank you for looking into this issue. I am also using the AnuPpuccin theme without any style overrides (completely styled using only Style Settings plugin), on Windows 11.

I am still able to reproduce this issue after pulling the latest commit in `main` and configuring the added setting. Pictured below are my current style settings (after closing and reopening) as well as the left menu where the issue still occurs.

![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/27722166/c31ea6dd-1304-49a8-9388-5836fdcba1b0)

**Comment by jprateragg** [comment]
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/3075374/92baf447-3577-402c-a224-179234b1a9ba)

I can confirm I'm also having the same issue. The nesting is still off. I have confirmed I have the same settings as @julianjuko

**Comment by RicaInWanderland** [comment]
Thank you for the update.

However, I'm still experiencing the same problem as @jprateragg and @julianjuko.

The only workaround I have currently is to:
- disable "folder icons for collapse indicators"
- install "Icon Folder" from community plugin and manually rename all folders and add the folder icon .

But that's kind of tedious and the folder icon doesn't change regardless of collapse/expand mode.
