### ISSUE TITLE
[Feature Request] Color suggestions

### ISSUE THREAD

**Issue by iris2jane** [AnubisNekhet/AnuPpuccin#22]
In light mode, white is not too obvious in the light background. 
Maybe it is better to use a deeper color instead of white. What do you think?
Thanks for making such an elegant theme!

![截图_20230106101819](https://user-images.githubusercontent.com/36763930/210916498-8c030085-1ac5-4a68-8500-f9401030a9f6.png)

**Comment by AnubisNekhet** [comment]
Fixed with v1.2.7
