### ISSUE TITLE
[Bug] The "custom callout" snippet does not reproduce the callout icons when the icon is taken from as SVG repository. 

### ISSUE THREAD

**Issue by smna-eeallatonce** [AnubisNekhet/AnuPpuccin#224]
The "custom callout" snippet does not reproduce the callout icons when the icon is taken from as SVG repository. 

I have created a lot of custom callouts, many of which using an icon taken from a SVG repository online. All of the sudden the icons stopped showing, but only for these icons (those from lucide still work).

**Comment by trainbuffer** [comment]
If you are talking about the `--callout-icon: '<svg>...custom svg...</svg>';` format, it _appears_ a recent installer (Electron) update broke them. You can read the conversation here (about 20 posts):

https://discord.com/channels/686053708261228577/702656734631821413/1152434783343890592

**Comment by AnubisNekhet** [comment]
Closing this issue since it does not concern the theme itself

**Comment by trainbuffer** [comment]
Seems fixed now using the latest installer.
