### ISSUE TITLE
How to style Obsidian-internal and external links differently?

### ISSUE THREAD

**Issue by pinetreemoonlight** [AnubisNekhet/AnuPpuccin#225]
Apologies for posting, since this is not a bug or anything, just my incompetence. 

Using Anupuccin theme, I would like internal links and external URL's to have different colors. I tried playing around with various bits of the theme css, but was not successful. Any help is appreciated!

**Comment by trainbuffer** [comment]
Here is fine (I think), but I'd ask on the forum or Discord 👍🏼
