### ISSUE TITLE
[Feature Request] Variable lenght for header divider depending on header level

### ISSUE THREAD

**Issue by ferife** [AnubisNekhet/AnuPpuccin#228]
Option in style settings for header dividers to vary by length based on header level, with level 1 headers having dividers that go all across the page and level 6 headers having either no divider or a divider that is very short

This is a feature that the [ITS theme](https://github.com/SlRvb/Obsidian--ITS-Theme) has, which I would like to see in AnuPpuccin

[Here](https://imgur.com/a/z2ggaFa) is a screenshot of what this looks like in ITS

**Comment by AnubisNekhet** [comment]
Marking this as unplanned since headings in AnuPpuccin use `border-bottom` for divider implementation, which are pretty difficult to work with regarding varying length.
