### ISSUE TITLE
[Bug] Issue in codeblock numbering

### ISSUE THREAD

**Issue by pgyogesh** [AnubisNekhet/AnuPpuccin#23]
**Describe the bug**
If we have a long code line and when the line gets wrapped. Number is aligned to second line of wrapped of line.
**To Reproduce**
1. Create a codeblock with long line

**Expected behavior**
- Number should be aligned to first line
- 
**Screenshots**
![Screenshot 2023-01-05 at 1 36 23 PM](https://user-images.githubusercontent.com/18283952/210945387-779e0e9d-2c5f-4a05-8826-564808d03a9e.png)

**Comment by AnubisNekhet** [comment]
I've set the number to align itself at the top, it should come with the next release.
