### ISSUE TITLE
[Bug] Amoled Dark theme makes code snippet impossible to read

### ISSUE THREAD

**Issue by mathisgauthey** [AnubisNekhet/AnuPpuccin#236]
**Describe the bug**
Hello there !
I'm using the AMOLED dark version of the dark theme on my Asus OLED laptop.
It turns out that in dark mode, I can't see any code snippet whereas it is possible in light mode.

**To Reproduce**
Use amoled dark mode.

**Expected behavior**
Code snippet should have an aura surrounding the text.

**Screenshots**
Light mode, we can see the code snippets : 
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/46576952/a08e99ec-23cd-424e-b366-8951452bba28)

Dark mode, we can't : 
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/46576952/d2a71b39-d9b9-4de9-867a-bbb3c4113fd7)

**Additional context**
Settings : 

Style settings : 
```
{
  "anuppuccin-theme-settings@@anp-alt-rainbow-style": "anp-full-rainbow-color-toggle",
  "anuppuccin-theme-settings@@anp-custom-checkboxes": true,
  "anuppuccin-theme-settings-extended@@anp-theme-ext-amoled": true,
  "anuppuccin-theme-settings-extended@@anp-theme-ext-dark": true,
  "anuppuccin-theme-settings-extended@@anp-theme-ext-light": true,
  "anuppuccin-theme-settings@@anp-codeblock-numbers": true,
  "anuppuccin-theme-settings-extended@@catppuccin-theme-extended": "ctp-nord-light",
  "anuppuccin-theme-settings-extended@@catppuccin-theme-dark-extended": "ctp-nord-dark",
  "anuppuccin-theme-settings@@anuppuccin-accent-toggle": true
}
```

EDIT: I'm pretty sure that this is going to look well on an IPS screen. My question is two-sided : 
- How can I lighten the border so that I can see my codes snippet aura/halo on my OLED screen ?
- Is this possible to add these changes so that user having AMOLED mode activated automatically changed some color or transparency so that the boxes are more visible.

ANOTHER EDIT: 
- I get the issue. I asked a friend to verify on his end with an IPS screen. The color scheme is putting darker shades of black for the code snippet. Which obviously doesn't work with OLED screens. Hence my proposed solution : Reverse the background of the code and the actual background on AMOLED DARK mode,
It will then show the code snippet with a sort of "greyed" halo while most of the screen stays pitch black.

Thanks in advance !

**Comment by AnubisNekhet** [comment]
Hi there!
Thanks for pointing out the issue! I'm really sorry for not paying more attention to how the colors interacted with each other on different screens. Right now, AnuPpuccin is on hiatus, but I'll get around to fixing it very soon!
For the time being, you can use this snippet:
```
body {
  --code-background: rgba(var(--ctp-surface0));
}
```
This should give your codeblocks a lighter color while still being readable enough against the text color.

**Comment by mathisgauthey** [comment]
> Hi there! Thanks for pointing out the issue! I'm really sorry for not paying more attention to how the colors interacted with each other on different screens. Right now, AnuPpuccin is on hiatus, but I'll get around to fixing it very soon! For the time being, you can use this snippet:
> 
> ```
> body {
>   --code-background: rgba(var(--ctp-surface0));
> }
> ```
> 
> This should give your codeblocks a lighter color while still being readable enough against the text color.

Hey there, thanks for the input !

I'm using an automated way of switching theme on my computer, so I'd need to switch it manually each time this way.

So thanks, but I'll wait for it to be implemented and linked through the AMOLED dark and dark theme settings 💪

**Comment by AnubisNekhet** [comment]
No worries, this should help you isolate it to AnuPpuccin, specifically AMOLED:
```css
.theme-dark.anp-theme-ext-amoled {
  --code-background: rgba(var(--ctp-surface0));
}
```

**Comment by mathisgauthey** [comment]
> No worries, this should help you isolate it to AnuPpuccin, specifically AMOLED:
> ```css
> .theme-dark.anp-theme-ext-amoled {
>   --code-background: rgba(var(--ctp-surface0));
> }
> ```

![2023-11-22 13_16_15.jpg](https://github.com/AnubisNekhet/AnuPpuccin/assets/46576952/0e1f1c02-1308-4731-95ef-5a54327ea5dc)
