### ISSUE TITLE
[Feature Request] Wrap and No Wrap lines in codeblock

### ISSUE THREAD

**Issue by pgyogesh** [AnubisNekhet/AnuPpuccin#24]
**Feature Description**
- An option to enable and disable line wraps in code block

**Comment by AnubisNekhet** [comment]
Could you elaborate on this feature a bit more?

**Comment by pgyogesh** [comment]
Sorry, I wanted to say word wrap instead of line wrap.

More:
https://www.computerhope.com/jargon/w/wordwrap.htm

**Comment by AnubisNekhet** [comment]
I've added an option to disable line wraps in code blocks and made them scrollable, though this will not work with code blocks in preview mode with syntax highlighting.

**Comment by AnubisNekhet** [comment]
It's available on the repository, and it should come with the next theme release as well! 😁

**Comment by AnubisNekhet** [comment]
Added with v1.2.8 :)
