### ISSUE TITLE
[Bug] Task status is not working

### ISSUE THREAD

**Issue by haShinui** [AnubisNekhet/AnuPpuccin#243]
**Describe the bug**
The costume statuses that should come with this theme dont work. I installed snippets here in the github and restarted obsidian many time. I tried different ways to solve it, in another vault and son on but nothing worked.

**To Reproduce**
1. Install AnuPpuccin theme and tasks
2. Go to tasks setting and add AnuPpuccin custom statuses
3. Restart obsidian
4. See that doesnt matter what symbol you put in, it counts as check

**Expected behavior**
That it works as shown

**Screenshots**
here before render, 
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/67230963/74d08f90-37e6-46f7-92ec-a05fdfd87442)
now after putting space in 
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/67230963/320b397d-b999-4764-b2df-4a35085baf14)
it doesnt matter if reading or edit mode.

**Comment by haShinui** [comment]
Solved it, took me hours to figure it out but style settings were somehow at fault, even when the settings were at default.

**Comment by elasticroentgen** [comment]
~~@haShinui can you elaborate on how you fixed this? i have the same issue.~~

Nevermind found it. One has to enable "Custom Checkboxes" via Style Settings in the "file Editor" section.
