### ISSUE TITLE
Where did the custom background go? [Bug] 

### ISSUE THREAD

**Issue by moonyuno** [AnubisNekhet/AnuPpuccin#247]
Hello!
So, today I updated the Anuppuccin plugin, just to realise, that my background was all white now. I looked up the custom background setting in the style settings, just to find out that it disappeared. 
Is this a bug or was it on purpose?

**Comment by AnubisNekhet** [comment]
The custom background feature has been moved to [this snippet](https://github.com/AnubisNekhet/AnuPpuccin/blob/main/snippets/custom-background.css) to comply with obsidian theme guidelines.
