### ISSUE TITLE
Floating status bar hides the status bar all together[Bug] 

### ISSUE THREAD

**Issue by pattystefy** [AnubisNekhet/AnuPpuccin#248]
Hello! Today when I updated my obsidian, the status bar disappeared. I turned off all plugins and snippets and it turns out that the floating status bar snippet causes this issue. All you need is to activate it, and the bar slides into a corner and disappears. I suppose the update affected this particular snippet.

**Comment by AnubisNekhet** [comment]
Hi there,
That is a feature of this theme (primarily to remove objects obstructing the workspace).
You simply hover over the space where it is supposed to be and it will display.
![in action](https://media.discordapp.net/attachments/855181471643861002/1072583410549260389/wsilgQN.gif?ex=65a6c9a4&is=659454a4&hm=b86567a0a468b228cc9b9eee085165c630b93eb41212adb695bacb8aa35054d3&=&width=1124&height=624)

**Comment by pattystefy** [comment]
Oh I see. I'm sorry, my bad! Thank you for your respone
