### ISSUE TITLE
[Bug] Adding image to custom background

### ISSUE THREAD

**Issue by cs-mshah** [AnubisNekhet/AnuPpuccin#25]
How can we add a custom image to the Custom background style settings? The option species to have the image url in the format:
`url("https://")`. But how can we add a downloaded image? I tried putting the path to the downloaded image inside the `url()` but it didn't work. Or is it that it only accepts images online? 

I wanted a plain background instead of the one that comes by turning on that option. More like the Obsidian nord dark theme but with a translucent glass like background. Can you please tell how can this be achieved?

**Comment by AnubisNekhet** [comment]
Using local files in CSS is kind of tricky since they use relative paths and it really depends on the OS you use. For now, you can only use hosted images but I'll be looking out for methods to allow the use of local files 😊

**Comment by JettyLee17** [comment]
There's a solution,you can use this format below:
**url("app://local/+the local address of image")**

There's my example:
**url("app://local/D:/ObsidianDataBase/background.jpg")**

**Comment by LinuCC** [comment]
> There's a solution,you can use this format below: **url("app://local/+the local address of image")**
> 
> There's my example: **url("app://local/D:/ObsidianDataBase/background.jpg")**

Note that this won't work starting with Obsidian 1.2.8 because of this change (At least for me):

> Removed support for app://local URLs. These were reported as a potential vulnerability when using iframes.
