### ISSUE TITLE
[Bug] Custom task icons not rendering properly

### ISSUE THREAD

**Issue by breannar888** [AnubisNekhet/AnuPpuccin#251]
The custom status icons for tasks do not render after installing the Task plugin and adding the custom tasks to the Custom Statuses section. 

**To Reproduce**
1. Go to 'Community Plugin' section and click on 'Tasks'
2. Scroll down to 'Custom Statuses' section and click on 'AnuPupuccin Theme: Add 28 supported statuses'
3. Restart Obsidian to update task settings
4. Try to create one of the custom themes ( - [!] , - [>], - [*] ). They will show with the native completed task icon instead of the custom one

**Expected behavior**
Once installing AnuPpuccin and adding custom statuses configuration to Tasks, should see the custom status icons render properly when creating new tasks

**Screenshots**
Attached Video 
<img width="646" alt="Screenshot 2024-01-14 164612" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/67029835/f419fe42-4417-467d-88e4-081a78ec3885">
<img width="657" alt="Screenshot 2024-01-14 164630" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/67029835/671c4187-d0e2-468c-9bb6-b4868d46529b">
<img width="905" alt="Screenshot 2024-01-14 183254" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/67029835/65841973-6b88-4a46-ad0a-f60e5e19a3cc">

**Additional context**

**Comment by AnubisNekhet** [comment]
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/102488279/7ef11a2e-5f71-4514-96c3-13afc447dba2)

Have you enabled this option?

**Comment by breannar888** [comment]
Enabled that option, seeing the custom icons now. Thank you for your help!
