### ISSUE TITLE
[Feature Request] Any way to change inline code color via Style Settings?

### ISSUE THREAD

**Issue by warm-july** [AnubisNekhet/AnuPpuccin#252]
**Feature Description**
Lovely way to change almost every color except for inline code using backticks `LIKE THIS`, can we make it possible to change that as well?
Thank you!

**Comment by AnubisNekhet** [comment]
You can change the default code text color via `File Editor & Markdown elements > Codeblocks > Codeblock Text Color`:
<img width="376" alt="image" src="https://github.com/AnubisNekhet/AnuPpuccin/assets/102488279/defc602e-1c02-4fc1-80ec-e73c4c2346da">
