### ISSUE TITLE
[Feature Request]  Hover Line Indicator

### ISSUE THREAD

**Issue by lucasbcgeo** [AnubisNekhet/AnuPpuccin#256]
I saw this feature in Border Theme by [Akifyss](https://github.com/Akifyss) and i think this could be a great idea to this theme

https://github.com/Akifyss/obsidian-border?tab=readme-ov-file#hover-line-indicator

=)

**Comment by AnubisNekhet** [comment]
Closing as unplanned due to time constraints (#204). I might work on a snippet to achieve this but no guarantees.
