### ISSUE TITLE
[Readme enhancement] Link capacities-callouts in the readme

### ISSUE THREAD

**Issue by enderprism** [AnubisNekhet/AnuPpuccin#257]
how was this "panel" formatting done? are there any plugins used? i'd like to format documents like this but i can't find the information anywhere…

![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/76617157/5b8eb365-5ce4-4107-8d89-1e70285cc0ac)

**Comment by enderprism** [comment]
i found the name of this kind of thing! it's called [Wiki-Style Callouts](https://www.reddit.com/r/ObsidianMD/comments/13ytnm8/a_clean_wiki_style_callout_box/?sort=new )

**Comment by enderprism** [comment]
nevermind, it's actually this: https://gist.github.com/AnubisNekhet/9e5c9b2440e102b96f94372194d5781c

**Comment by enderprism** [comment]
could it be linked in the readme?

**Comment by AnubisNekhet** [comment]
I haven't linked that specific snippet in the README since it was pretty experimental and unfinished. Linking it might create more confusion about the theme. Hope this helps!
