### ISSUE TITLE
[Feature Request] Outline styling?

### ISSUE THREAD

**Issue by nyhryan** [AnubisNekhet/AnuPpuccin#273]
**Feature Description**
![yONDIrV6Nz](https://github.com/AnubisNekhet/AnuPpuccin/assets/85018069/d81183e1-b3ca-4aa4-a1cc-e670befeab13)
It would be nice if I can **disable folder icons in Outline core plugin** ~~and make vertical guidelines more visible like in the default theme in the right.~~

**Comment by nyhryan** [comment]
I've found out I can adjust `.tree-item-children` class's `border-left` property for making vertical guidelines more visible.

**Comment by DudeThatsErin** [comment]
Is this still an issue @nyhryan ?

**Comment by nyhryan** [comment]
OH I think it's all good now I don't know why I had this issue still open oops sorry
