### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by THT412** [AnubisNekhet/AnuPpuccin#274]
**Describe the bug**
I try to use the Rainbow File snippets but it doesn't show up.

**To Reproduce**
I downloaded the snippets file and installed everything as told
I also did import this custom style setting: https://www.reddit.com/r/ObsidianMD/s/gldCyKioTQ
But it seems to work perfectly fine in the post.

**Screenshots**
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/164471591/92d14104-fe87-4375-ae55-33ab0ba136c1)
Here are my settings:
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/164471591/4767b266-1b4d-4dd2-8498-03d349ba7878)
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/164471591/1d05b642-4131-48f9-a782-25035333e75d)

**Comment by domizianooo** [comment]
As stated in #278, rainbow folders seem to be broken for everyone in this version. You can rollback to the previous version (1.4.5) if you find them essential (like me lol) until they will be fixed

**Comment by DudeThatsErin** [comment]
Works for me. Is this still an issue?

**Comment by THT412** [comment]
> Works for me. Is this still an issue?

I've just checked. And nope no issues, it works fine now. Thanks
