### ISSUE TITLE
[Bug] Rainbow Folders do not work

### ISSUE THREAD

**Issue by apertureless** [AnubisNekhet/AnuPpuccin#278]
**Describe the bug**
After the update and reset of the styles, the Rainbow Folders are not working anymore. I enabled the option it kinda changes some margins but no color appear.

![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/4975917/61b6fa6a-ba3e-46d7-ba57-7284d1b392f2)

**Comment by apertureless** [comment]
If I change it from full to simple, only the toggle indicators are colored, not the text.  And in `full` nothing is colored.

**Comment by agopwns** [comment]
same problem

**Comment by nocean** [comment]
Also have this problem.

**Comment by mayankkalbhor** [comment]
Same issue not working

**Comment by GuMengSama** [comment]
Same problem here.

**Comment by MarcosCyberX** [comment]
Same problem here.

**Comment by atg-abhishek** [comment]
Experiencing the same issue, has anyone found a good solution for this?

**Comment by magpie514** [comment]
> Experiencing the same issue, has anyone found a good solution for this?

You can always roll back to a previous version, just replace the theme and manifest in the themes folder in .obsidian. Not ideal, but should do the trick until this is addressed.

**Comment by magpie514** [comment]
> Experiencing the same issue, has anyone found a good solution for this?

You can always roll back to a previous version, just replace the theme and manifest in the themes/anuppuccin folder in .obsidian. Not ideal, but should do the trick until this is addressed.
I rolled back to 1.4.5 (in releases).

**Comment by whiterqbbit** [comment]
@magpie514 

I can't find that folder inside .obsidian, is the path `~/.obsidian/themes` ?
Thanks for the tip !

**Comment by magpie514** [comment]
> @magpie514
> 
> I can't find that folder inside .obsidian, is the path `~/.obsidian/themes` ? Thanks for the tip !

It's the path of your vault. In my case it's `/home/magpie/Documents/Obsidian/.obsidian/themes/AnuPpuccin/` but yours will be different.
You can right-click on any file *(or folder?)* and select "Show in system explorer". The .obsidian folder is at the root of the vault, so if you click a file deep inside the vault, go back a few levels as necessary.
You can also use your system's search and look for "AnuPpuccin".

*(Yes,  I wasn't thinking too hard when naming my Obsidian vault)*

**Comment by raven2cz** [comment]
It is after update to new version of obsidian 1.6.2.

**Comment by magpie514** [comment]
Yeah updating to the newer version "fixes" the issue.  It was targeting a then unreleased (to the public) version of Obsidian. It was never broken, it was just fixed for a version that wasn't out (publicly) yet.

To those that rolled back, it's time to update, can confirm it works as expected.

**Comment by apertureless** [comment]
I can confirm, they are working again.

**Comment by vcuenot** [comment]
hello, the bug appeared today in my obsidian, i updated it to version 1.6.3 and reset the plugin but nothing changed.

**Comment by graysodacan** [comment]
also experiencing this bug in version 1.6.3 :,))

**Comment by AlexMC** [comment]
Seeing the same since 1.6.3

**Comment by francisrl** [comment]
Had the same problem using Obsidian 1.6.3. Updating community theme (AnuPuccin) fixed the issue! 

Settings / Appearance / Current community themes / Check for updates

**Comment by graysodacan** [comment]
> Had the same problem using Obsidian 1.6.3. Updating community theme (AnuPuccin) fixed the issue!
> 
> Settings / Appearance / Current community themes / Check for updates

can confirm that it works again after updating!
