### ISSUE TITLE
[Bug] Text color of stacked tabs makes them barely visible when focused, but is fine when window is unfocused

### ISSUE THREAD

**Issue by Ktar5** [AnubisNekhet/AnuPpuccin#28]
**Describe the bug**
The text color of stacked tabs in dark mode using the style settings and the extended colors, when the window is unfocused the text color seems perfectly correct, however when in focus, the stacked tabs have the wrong color and make the text very hard to see

**To Reproduce**
1. focus window
2. have stacked tabs
3. see tab titles as hard to see

**Expected behavior**
White text to be easy to see

**Screenshots**
Unfocused window:
![Obsidian_biSAqDZ0YX](https://user-images.githubusercontent.com/1613876/211131420-b56fa544-9ac8-47b2-af7f-56f0a8210c2a.png)

Focused window:
![image](https://user-images.githubusercontent.com/1613876/211131456-b6685634-34b0-483a-8da4-a34843e449ea.png)

**Comment by AnubisNekhet** [comment]
Fixed with the latest update 😊
