### ISSUE TITLE
Permission to post Simple Rainbow css as a snippet

### ISSUE THREAD

**Issue by ms3056** [AnubisNekhet/AnuPpuccin#280]
Hello - I have created a Rainbow Folders snippet from your theme and added a few other bits and pieces as a snippet. It is located here: 

https://github.com/ms3056/Snippets/blob/main/Files.css

I put a reference to your code, your buymeacoffee, and made a clear statement that this is YOUR code that I edited. If this is not sufficient, or if you simply do not want me to post it, I will remove it immediately and you have my apologies. 

I even left the Style Settings menus the same (and added a setting of my own). 

I hope this is OK, and if it is not, I humbly apologize and will remove it post haste.

**Comment by AnubisNekhet** [comment]
I see no issue 😄
You can do whatever you want with my code as long as you keep the license and attribution, that's what the license permits.

**Comment by ms3056** [comment]
Thank you!
