### ISSUE TITLE
[Bug] Cancelled tasks do not work

### ISSUE THREAD

**Issue by foegra** [AnubisNekhet/AnuPpuccin#294]
Tasks are being displayed as regularly "done" tasks

**Comment by AmmarCodes** [comment]
Have you checked that "Enable Custom Checkboxes" option is turned on?

You can reach it through Settings > Style Settings > AnuPpuccin > File Editor & Markdown Elements > Checkboxes

![image](https://github.com/user-attachments/assets/9a8aadd8-030c-4655-abe1-39646680ad24)

**Comment by DudeThatsErin** [comment]
@foegra is this solved?

**Comment by foegra** [comment]
> Have you checked that "Enable Custom Checkboxes" option is turned on?
> 
> You can reach it through Settings > Style Settings > AnuPpuccin > File Editor & Markdown Elements > Checkboxes
> 
> ![image](https://private-user-images.githubusercontent.com/351256/356957381-9a8aadd8-030c-4655-abe1-39646680ad24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzU3ODQsIm5iZiI6MTcyNDEzNTQ4NCwicGF0aCI6Ii8zNTEyNTYvMzU2OTU3MzgxLTlhOGFhZGQ4LTAzMGMtNDY1NS1hYmUxLTM5NjQ2NjgwYWQyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwNjMxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2RiODRmNDk0Y2M5ODg3MDYwYzkyYTAwMmJlNjQwZWQwODFkM2U0NTgzMzNhNzkxMGZhMWM5MjMwMjE5ZmI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JG777qYWGzOYJaiM1KJosbs6MbqzM5Dzw9UzepEEiCU)

I will look into that, thank You
