### ISSUE TITLE
[Bug] External link icons are not displayed

### ISSUE THREAD

**Issue by Rikiub** [AnubisNekhet/AnuPpuccin#300]
**Describe the bug**
Default theme display icons on external links but AnuPpuccin doesn't. It's good have icons for accessibility because help to difference between internal and external links.

**To Reproduce**
1. Switch to Anuppuccin Theme
2. Write an [external link](https://example.org).

**Expected behavior**
Link with external icon like the default theme.

**Screenshots**

Default theme
![markup_25258.png](https://github.com/user-attachments/assets/471d032c-850e-46f2-94db-28bb6c7824e8)

AnuPpuccin theme
![markup_25262.png](https://github.com/user-attachments/assets/0fd8e540-e0b7-4720-8c69-b54e4676bbfa)

**Comment by iwa** [comment]
(can be closed as PR's merged)
