### ISSUE TITLE
[Bug] The custom checkboxes feature doesn't seem to be working.

### ISSUE THREAD

**Issue by Mack127444** [AnubisNekhet/AnuPpuccin#303]
**Describe the bug**
When I type the correct syntax for custom checkboxes (like - [9] or stuff like that), I only get a regular ticked box (with no strikethrough). The same issue was had with the Primary theme, until I opened an issue ticket and they updated it.

**To Reproduce**
1. Type any of the syntax for the custom checkbox (like - [n] for note)
2. It just becomes a regular ticked box (no strikethrough).

**Expected behavior**
It should be an icon of some sort, instead of the ticked box.

**Screenshots**
A quick video of my problem. (Yes, the theme is updated to the latest version at the time of this issue post).
https://github.com/user-attachments/assets/28d4378b-b276-4f3a-a224-8c5ed62f8e12

**Additional context**
Its unlikely that this is on my end, as other themes like Primary, Things, and Minimal are all working in terms of these custom checkboxes.

**Comment by AmmarCodes** [comment]
Have you checked that "Enable Custom Checkboxes" option is turned on?

You can reach it through Settings > Style Settings > AnuPpuccin > File Editor & Markdown Elements > Checkboxes

![image](https://github.com/user-attachments/assets/9a8aadd8-030c-4655-abe1-39646680ad24)

**Comment by DudeThatsErin** [comment]
<img width="127" alt="Screenshot 2024-08-19 at 9 26 40 PM" src="https://github.com/user-attachments/assets/0bc2d696-21f1-4b15-aacd-07f9a16e7833">

Works for me. That is this:

```
- ["] dd
```

**Comment by Mack127444** [comment]
That fixed the issue, I don't know how I didn't notice that before. Thank you!
