### ISSUE TITLE
[Feature Request] Way to disable the space added after 4 spaces

### ISSUE THREAD

**Issue by PolyCatDev** [AnubisNekhet/AnuPpuccin#304]
**Feature Description**
I was thinking about a toggle in style setting to disable the fake space added after indenting a word by 4 spaces.

**Additional context**
![Screencastfrom2024-09-1814-34-29-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/cacd9710-36ba-42c5-a211-04579cd37ed7)

**Comment by notnotnescap** [comment]
unable to reproduce, are you sure this is not caused by another plugin? are you on the latest version?

**Comment by PolyCatDev** [comment]
After some testing I realized that it's some setting I flicked in style settings. If i reset to default it fixes itself. Seems that the toggle I was looking for already exists.
