### ISSUE TITLE
[Feature Request] Style Settings option: code blocks -> code text color

### ISSUE THREAD

**Issue by Criamos** [AnubisNekhet/AnuPpuccin#31]
**Feature Description**
A color setting similar to the "Minimal"-theme (with Style Settings plugin) that enables the user to change the
- `Code text color` (**only active when syntax highlighting is not present**)

**Miscellaneous Features**
- Some users might also love to change the `Code background color`

**Additional context**
For reference - the aforementioned feature in the "Minimal"-theme Style Settings (see: Style Settings -> Minimal -> Code blocks) looks like this:
![Obsidian_ClS9Ar5447](https://user-images.githubusercontent.com/981166/211683713-3376500f-3ffa-444f-a3fd-8f16f0b8a3ad.png)

I've used this feature to give my single-line code blocks (`the single backtick code blocks don't get syntax-highlighted most of the time`) a slightly more colorful hue to make them stand out a little bit more from normal text.

----
P.S.: 
You've developed a lovely theme! I especially like the extended color-schemes in combination with the "simple" rainbow folder colors. Makes it really easy to keep track of in which folder structure I'm currently in. 
**Thank you** for taking the time out of your day and sharing your work with the Obsidian community! 💟

**Comment by AnubisNekhet** [comment]
I've added an option to set custom colors for both, and it should be available with the next release. Hope that helps! 😊

**Comment by AnubisNekhet** [comment]
Added with v1.2.8 :)

**Comment by Criamos** [comment]
Thank you a lot! :)

An observation I just made while testing out `code text` colors:
It works great in Obsidian's "reading"-mode, but doesn't reliably recolor text in `live-preview` nor `source`-viewing-mode.
The only elements where `code text` gets the overwritten color in live-preview mode is transclusions and callouts. If you use a code block `within a normal sentence, like this,` it stays at the default color.

**Comment by AllanFerencz** [comment]
Related is the PDF export for code. Inline it's hard to read and the background field doesn't seem to change the color it exports.

Example
![image](https://user-images.githubusercontent.com/16922988/212742464-54362f33-ed13-4f09-b4db-42223357cfe1.png)

**Comment by Zabooby** [comment]
I can't seem to find the option to change the colour of highlights.

**Comment by AnubisNekhet** [comment]
> I can't seem to find the option to change the colour of highlights.

I don't plan to support changing highlight colors right now since they add quite a lot of classes to the mix and it can get quite messy, sorry if that's an inconvenience 😅

**Comment by Zabooby** [comment]
> > I can't seem to find the option to change the colour of highlights.
> 
> I don't plan to support changing highlight colors right now since they add quite a lot of classes to the mix and it can get quite messy, sorry if that's an inconvenience 😅

No problem, it's not a deal-breaker for me.
