### ISSUE TITLE
[Feature Request] add setting for custom Live Preview editor font

### ISSUE THREAD

**Issue by trainbuffer** [AnubisNekhet/AnuPpuccin#32]
_Style Settings>Components>Editor_ has a setting for custom source editor font, but it would be nice to set a custom Live Preview editor font for those who mostly stick to Live Preview and Reading modes.

**Comment by AnubisNekhet** [comment]
I can definitely set a customizable font for Live Preview but afaik isn't it supposed to mirror reading mode? Either way, it's pretty easy to implement and it should be done pretty easily 😁

**Comment by trainbuffer** [comment]
I like to have LP and Reading fonts different (is that weird? :D), so set the Reading mode in Obsidian's settings and have been using `.markdown-source-view .cm-editor .cm-scroller {}` to set a custom LP font -- which works fine, but a setting would be nice -- one less snippet to worry about 😵‍💫

**Comment by AnubisNekhet** [comment]
Added with v1.2.8 :)
