### ISSUE TITLE
[Bug] Can't find option to use a custom icon for a folder

### ISSUE THREAD

**Issue by livingmoth** [AnubisNekhet/AnuPpuccin#321]
I can't find the option in either the file browser tab nor the rainbow folder settings tab...help
![image](https://github.com/user-attachments/assets/523b7574-f578-43b3-8de2-6a90ee309318)
![image](https://github.com/user-attachments/assets/9275c70d-3217-4d2d-ba13-5b14819b41c2)

**Comment by notnotnescap** [comment]
There is no AnuPpuccin feature to use custom icons afaik. You can use [Iconize](https://github.com/FlorianWoelki/obsidian-iconize) for that.

**Comment by livingmoth** [comment]
Thanks!!

**Comment by notnotnescap** [comment]
Hello, please close this issue since it is resolved and Anubis is very busy
