### ISSUE TITLE
[Bug] code block line breaks not preserved in reading view

### ISSUE THREAD

**Issue by syrth-io** [AnubisNekhet/AnuPpuccin#34]
**Describe the bug**
when switching from editing view to reading view, line breaks in code blocks are not preserved and all lines contract into one, regardless of whether line wrap is on or off in style settings.

**To Reproduce**
1. create a code block in editing mode (either source or live preview)
2. insert carriage return between lines of text
3. switch to reading mode to see effect

**Expected behavior**
for line breaks to be preserved in reading view as usual.

**Screenshots**
source editor vs reading mode vs live preview in AnuPpuccin:
![code block in source editor](https://i.imgur.com/c7aoxrG.png) ![same code block in reading view](https://i.imgur.com/Ud7871l.jpg) ![same code block again but in live preview](https://i.imgur.com/E5WXo6F.png)

source editor vs reading mode with all themes disabled (similar results in other community themes):
![code block in source editor](https://i.imgur.com/ZPlPfsz.png) ![same code block in reading view](https://i.imgur.com/FTCQAJ2.png)

**Additional context**
I admittedly can't remember if this started before or after I toggled line wrap on/off as I didn't have a page with any code blocks open at the time. this is the same regardless of theme variation or opening/closing Obsidian. (not as important, but as you can see, the padding inside of non-reading view code blocks is... pretty padded, too, haha.)
I also toggled all my plugins off to see if there was some interference somewhere, but that had no effect.

thank you for all the work you've done on this theme! I've been using it since before it was (back) on the community store and am so delighted by all the updates and features & always so excited to see new updates.

**Comment by AnubisNekhet** [comment]
Fixed with the latest commit, line breaks should be preserved as normal now; I've split the wrap option into preview and edit modes for more convenience 😊

**Comment by syrth-io** [comment]
working beautifully now, thank you!
