### ISSUE TITLE
[Bug] Code Block Displaying Issue

### ISSUE THREAD

**Issue by Jack251970** [AnubisNekhet/AnuPpuccin#38]
This is the issue I found.
If the font size is smaller than 18(18 exluded), the language hints in code block preview mode will be displayed incompletely, and even disappear when the font size is 10.

This is my screenshot.
![Issues](https://user-images.githubusercontent.com/53996452/212542590-4ab7f9b2-5e63-4d0b-933b-ec0629a85554.jpg)

Thanks for all the work you've done on this theme, I really enjoy it!

**Comment by Defolters** [comment]
I have the same issue, but in my case code blocks are completely broken. Bug appeared in 1.2.8 version.
![Screen Shot 2023-01-16 at 18 47 19](https://user-images.githubusercontent.com/10363071/212832043-2fc5da11-977a-4ca2-9068-4f6e6d6538fb.png)

**Comment by AllanFerencz** [comment]
> I have the same issue, but in my case code blocks are completely broken. Bug appeared in 1.2.8 version. ![Screen Shot 2023-01-16 at 18 47 19](https://user-images.githubusercontent.com/10363071/212832043-2fc5da11-977a-4ca2-9068-4f6e6d6538fb.png)

This issue was mentioned [here](https://github.com/AnubisNekhet/AnuPpuccin/issues/40). It's not updated yet in the version but I looked at the code. It should fix the issue.

If you want to remove it you can inspect obsidian and turn off the property applying the styles. Since obsidian doesn't refresh unless you close it your session should maintain the correct look till you close it

**Comment by Jack251970** [comment]
After updating to version 1.2.8, the bug seems to get worse, and the language tips are even less visible.
Here is a screenshot comparison of the different versions.

![Obsidian Bugs](https://user-images.githubusercontent.com/53996452/213605695-b95c6461-fb3c-4b65-a6e3-a79fa44ba4ab.png)

**Comment by AnubisNekhet** [comment]
I've added a fix for this and it'll come with 1.2.9, sorry for not replying! 😭 I didn't notice this thread until now, sorry if that caused any major problems.

**Comment by Jack251970** [comment]
I seem to have misunderstood "[fix live preview language button visibility -] 38". I thought this issue was fixed in the 1.2.8 release.

But this issue really bothers me, and I hope it can be fixed sooner rather than later.🙇‍

**Comment by AnubisNekhet** [comment]
I've implemented fixes in 1.2.9, please let me know if your issue has been resolved 🙂

**Comment by Jack251970** [comment]
My problem does get fixed, thanks a lot!
Ｏ(≧∇≦)Ｏ
