### ISSUE TITLE
[Bug] No difference in `anp-embed` and `anp-embed-animated`.

### ISSUE THREAD

**Issue by pgyogesh** [AnubisNekhet/AnuPpuccin#4]
**Describe the bug**
I'm not noticing any difference between `anp-embed` and `anp-embed-animated`.

**To Reproduce**

- Embed markdown with  `anp-embed` and `anp-embed-animated`.
- There is no difference in both embeds

**Expected behavior**
- There should be differences between both styles.

**Comment by AnubisNekhet** [comment]
I see, I'll look into it.

**Comment by AnubisNekhet** [comment]
Replaced both styles with `seamless` embed style which can be used as `[!note|seamless]` in the new release.<br>
I think the previous styles were too complicated for a mere embed and i've opted for a more seamless embed style which blends into your note.
