### ISSUE TITLE
Code Blocks yellow bar [Bug] 

### ISSUE THREAD

**Issue by AllanFerencz** [AnubisNekhet/AnuPpuccin#40]
**Describe the bug**
When viewing coding blocks it has this yellow bar on it.

This looks related to the change made a few days ago ' overflow-x: scroll'
Link: https://github.com/AnubisNekhet/AnuPpuccin/blame/414181d38bfa2d469129bdd1c9f63ad54f849d46/src/modules/Note/codeblocks.scss

If I turn it off in the inspector it works as expected.

**Screenshots**
<img width="734" alt="image" src="https://user-images.githubusercontent.com/16922988/212740733-b85ff658-4816-4a39-b25d-78a0dadb7f61.png">

https://github.com/AnubisNekhet/AnuPpuccin/blame/414181d38bfa2d469129bdd1c9f63ad54f849d46/src/modules/Note/codeblocks.scss

**Additional context**

**Comment by AllanFerencz** [comment]
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/16922988/212741277-e0cda7e2-21a8-47e4-a603-10176d0db946.png">
What happens if I turn it off in the inspector

**Comment by AnubisNekhet** [comment]
I've added a fix for this in 1.2.9, please let me know if it's back to normal.

**Comment by AllanFerencz** [comment]
Yup all good now
