### ISSUE TITLE
[Bug] Speech bubbles not working as intended

### ISSUE THREAD

**Issue by pgyogesh** [AnubisNekhet/AnuPpuccin#42]
**Describe the bug**
Speech bubbles are broken.

**To Reproduce**
- Create a speech bubble
**Screenshots**
![image](https://user-images.githubusercontent.com/18283952/212811588-7beaf0a0-cefc-4154-ba45-b6df42803e89.png)

**Comment by AnubisNekhet** [comment]
Could you send the markdown of that specific part?

**Comment by AllanFerencz** [comment]
I was able to reproduce the issue.

```
- [0] Is this working correctly?
```

In Reading View
<img width="299" alt="image" src="https://user-images.githubusercontent.com/16922988/213538465-ee4c3bb7-588c-4866-91fe-58578b0d78cc.png">
Looks good

In Non Reading View
<img width="331" alt="image" src="https://user-images.githubusercontent.com/16922988/213538698-09f3b555-03e9-4685-8987-5643b5b4824d.png">

**Comment by AllanFerencz** [comment]
Don't have time to inspect it atm, but something with the padding and text indentation

<img width="282" alt="image" src="https://user-images.githubusercontent.com/16922988/213539367-f87cb707-f23c-49ec-97f8-8bcf69115776.png">

**Comment by AnubisNekhet** [comment]
ah, it's live preview then
i'll get to work on it, thanks for pointing it out!

**Comment by AnubisNekhet** [comment]
I've added fixes for this in 1.2.9, please let me know if it works.
