### ISSUE TITLE
[Feature Request] Adjustable font weight

### ISSUE THREAD

**Issue by bassamsdata** [AnubisNekhet/AnuPpuccin#46]
**Feature Description**
Adding font weight/thickness to the editor. 
Since many fonts do not work properly with the normal thickness of obsidian, this can also enhance how fonts are displayed.

**Miscellaneous Features**
I'm not sure how hard it would be to implement. But if it's hard, I think it would be enough to add a snippet.

**Additional context**
The purpose of this is just to enhance the reading experience in general.
Here is a photo from obsidian and other application (MarkText) for the same font, font size, and zoom level.

Obsidian on the left.
<img width="1290" alt="Screen Shot 2023-01-18 at 10 46 07 AM" src="https://user-images.githubusercontent.com/105807570/213222058-4af0caa3-6789-474a-af16-c6df10a28897.png">

Thank you for this wonderful theme.

edit: some typos and thanks

**Comment by AnubisNekhet** [comment]
This should be relatively easy to implement and it's a great idea, I'll get started on it soon!

**Comment by bassamsdata** [comment]
Thank you for all your work.
