### ISSUE TITLE
Plagiarism Blues

### ISSUE THREAD

**Issue by Nooby-001** [AnubisNekhet/AnuPpuccin#47]
Hi. It's a shame people are stealing your work, while I understand you not wanting to out the little rat, can you just give hints to which theme is it so we can delete it? Is it the one that looks almost like yours?

**Comment by AnubisNekhet** [comment]
Hi, I'd rather not deal with any drama or anything since it's just emotionally and mentally draining. I'd rather just ignore it since it would divert my mind from stuff I actually like doing. Sorry if it's any problem haha 😅

**Comment by Nooby-001** [comment]
Oops, I found it and gave them a (little) piece of my mind. Sorry I'll just delete their theme and ignore them.
Case closed!
