### ISSUE TITLE
[Feature Request] Export PDF colouring

### ISSUE THREAD

**Issue by AllanFerencz** [AnubisNekhet/AnuPpuccin#48]
**Feature Description**
Currently there is no way to alter the colour for 'Export PDF` that is separate from current theme (At least I couldn't find anything). PDF exports with a white background. This is a problem for readability as noted below in the screenshots.

When exporting I need change to the light mode and export as it's hard to read Dark mode export. It's also a problem with the accent colours. Any of the light ones on white look hard to read.

# Dark mode PDF
![image](https://user-images.githubusercontent.com/16922988/213873120-9639f24d-d284-4f5c-b854-f7348eed8f2f.png)
---

# Light mode PDF
![image](https://user-images.githubusercontent.com/16922988/213873091-dbd1de0c-27ee-4efc-a40d-ee6c189592d3.png)

Let me know if that makes sense. Some alternative solutions.
1. Make default export the light mode theme selected. 
2. Make the PDF background dark (I would personally still need to export in light then but at least it would be consistent. 

# Here are some more examples of darkmode export
![image](https://user-images.githubusercontent.com/16922988/213873679-81dd84f2-d225-4761-8d31-0c52472b8ca2.png)

**Comment by AnubisNekhet** [comment]
afaik this is an issue with the default theme as well, though i've made some adjustments to make it more readable in dark mode. the major problem is that the white background cannot be changed with any kind of CSS.
<img width="312" alt="image" src="https://user-images.githubusercontent.com/102488279/213880471-aa7cb15b-5c9e-4378-8f21-3fda576ae840.png">
If anyone has any idea on how to change the background, then please feel free to make a PR.

**Comment by AnubisNekhet** [comment]
Implemented with v1.3.0
