### ISSUE TITLE
Question : How to use Minimal cards snippet

### ISSUE THREAD

**Issue by issam-seghir** [AnubisNekhet/AnuPpuccin#49]
According to the note in the Style settings, I Install the [minimal cards snippet](https://github.com/kepano/obsidian-minimal/blob/master/src/scss/features/cards.scss )
but the obsidian doesn't recognize `.scss` in **appearance > CSS snippet**, so i change the extension to `.css`  and active the snippet but nothing changed in my dataview table even if I add in yml frontmatter `cssClass: cards`

**Update:**  
I open the `scss` snippet i vscode and compile the file then vscode create two files `cards.css.map` & `cards.css`
then open  obsidian and active `cards.css`  file and its worked

So, i have another question , can i do the same thing for [imag-grid.scss](https://github.com/kepano/obsidian-minimal/blob/master/src/scss/features/image-grid.scss) ? 
 and if not, can you support this please 🙃

**Comment by AnubisNekhet** [comment]
It works properly once compiled, you shouldn't have any problems :)
I suggest reading up on the [minimal theme documentation](https://minimal.guide/Block+types/Image+grids) to properly utilize it if you haven't.

**Comment by jimjam-slam** [comment]
For users who aren't familiar with SCSS, the [style file linked to in Style Settings](https://github.com/kepano/obsidian-minimal/blob/master/src/scss/features/cards.scss) needs to be compiled—that's a process that turns it into the CSS that Obsidian expects. If you try to provide the `.scss` file as is, it won't work (even if you change its file extension).

If you're not a developer and aren't comfortable installing a SCSS compiler yourself, beautifytools.com has one you can use online: https://beautifytools.com/scss-compiler.php

Copy and paste the content of the file into the left pane, hit "Compile scss", and then copy the content that comes out on the right into a file. Save it with a `.css` extension (eg. `cards.css`). Now restart Obsidian, go back to the Appearance pane, and you should see a toggle for the snippet!
