### ISSUE TITLE
[Bug] Custom checkbox doesn't show up

### ISSUE THREAD

**Issue by aasutossh** [AnubisNekhet/AnuPpuccin#54]
<img width="207" alt="image" src="https://user-images.githubusercontent.com/18498932/214259528-52a16f10-ad1e-4226-a627-7aa3da30c0aa.png">
looks like
<img width="151" alt="image" src="https://user-images.githubusercontent.com/18498932/214259582-a1730395-3045-42fc-ad3a-cb1c939231d3.png">

**Comment by AnubisNekhet** [comment]
You need to enable custom checkboxes using style settings.

**Comment by aasutossh** [comment]
I thought, I had enabled every feature, I don't know how I missed this. Thanks for this beautiful piece of work. <3
