### ISSUE TITLE
[Bug] Accents not changing when using Extended Colors 

### ISSUE THREAD

**Issue by BarryBurton57** [AnubisNekhet/AnuPpuccin#57]
When updating the palettes/schemes on Windows device using extended colors, the accent color does not change and remains the same as set in the style setting. Background color/styles update though, so the extended css is partly working. 

However, on Mac this works as expected. For example, changing style to Dracula will also force change accent color. 

This could certainly be a user error! Any help would be greatly appreciated.

**Comment by AnubisNekhet** [comment]
Are you:
1. Using the latest theme version?
2. Using the latest snippet version?
3. Enabled `Force custom accent`?
I believe I don't have any differences between operating systems for color variables, so it's hard to determine what might be the issue.

**Comment by BarryBurton57** [comment]
Hi Anu,

Thanks for coming back on this. 

Yes, all components are latest versions and `force custom accent` is enabled. 

It may down to some settings in my Vault on the Windows device. Either way, I rarely use that device so not too worried! Working fine on Mac.

Thanks for all your work. The theme is great!
