### ISSUE TITLE
[Feature Request] Hide metadata on certain notes

### ISSUE THREAD

**Issue by ProudBenzene** [AnubisNekhet/AnuPpuccin#58]
Hello, I wish the theme can have a solution to hide only the metadata of some given notes more conveniently.

Although there is currently an option to hide metadata in style settings, for me there are only a few notes whose metadata needs to be hidden, such as homepage; the metadata of other pages is also important for me to read my notes.

The The square orange icon in the corner can do the job of providing a choice, but every time I open the page I need to manually click the button, the operation will be slightly more frequent.

Thanks for the fascinating theme!

**Comment by AnubisNekhet** [comment]
The latest commit will hide metadata on notes that have the `hide-metadata` CSS class in their frontmatter.

**Comment by ProudBenzene** [comment]
> The latest commit will hide metadata on notes that have the `hide-metadata` CSS class in their frontmatter.

Thank you for the convenience!

**Comment by ProudBenzene** [comment]
> The latest commit will hide metadata on notes that have the `hide-metadata` CSS class in their frontmatter.

Hello, I have updated the latest version of theme just now and the cssclass fits very well! Thank you for this perfect theme, I hope this one gets better and better!
