### ISSUE TITLE
[Bug] No notion light theme flavour

### ISSUE THREAD

**Issue by pgyogesh** [AnubisNekhet/AnuPpuccin#66]
**Describe the bug**
I just downloaded latest extended colorscheme CSS file. I can see notion dark theme flavour but not light theme flavour.

**To Reproduce**
1. Download latest extended colorscheme CSS file.
2. Go to style setting
3. Try to select notion in light theme flavour

**Expected behavior**
I should be able to see the notion light theme flavour as I can see it in preview section on README.md

**Screenshots**

##### Light theme flavors

<img width="140" alt="image" src="https://user-images.githubusercontent.com/18283952/216261022-b5560496-f305-41b4-ba7b-d6a74d754b68.png">

##### Dark Theme flavors

<img width="211" alt="image" src="https://user-images.githubusercontent.com/18283952/216261133-956167f9-0a1e-4f0a-bbf4-f889e9f0d8bd.png">

**Comment by AnubisNekhet** [comment]
I've fixed the snippet, thank you for bringing it to my notice!

**Comment by pgyogesh** [comment]
Thanks, I can see notion in the dropdown list but choosing it doesn't changes the theme. In fact, If I choose any theme, It doesn't change.

Please note that I have already toggled the extended theme.

**Comment by AnubisNekhet** [comment]
Did you update to the latest version of the theme and enable the respective toggles?

**Comment by pgyogesh** [comment]
Yes, It works after apdating. Thanks
