### ISSUE TITLE
Select color theme

### ISSUE THREAD

**Issue by kleinptr9** [AnubisNekhet/AnuPpuccin#7]
Hello, how can I choose the right color theme?

Because I can set only Dark/Light and the major color which colors buttons and few other elements. When I open `theme.css` there is lot of disabled code which looks like yaml settings. But really not sure how to set it up..

**Comment by AnubisNekhet** [comment]
You'll need to use the style settings plugin to change themes.

**Comment by kleinptr9** [comment]
ok, thanks, would be nice to mention it in the readme.

**Comment by AnubisNekhet** [comment]
They are mentioned in the README at the bottom.
<img width="827" alt="image" src="https://user-images.githubusercontent.com/102488279/198633894-12e91f58-9ce3-469c-b070-b5e5f5ca214e.png">
