### ISSUE TITLE
[Bug] Unable to display the number of files

### ISSUE THREAD

**Issue by i-iooi-i** [AnubisNekhet/AnuPpuccin#71]
![image](https://user-images.githubusercontent.com/1827701/216753162-7d2ec4e8-696c-44d9-90fd-5033ebe7b4df.png)

HI, thank you for making such a wonderful theme. like it very much. 😍

I found a small mistake, maybe not a mistake. When the“Enable floating vault title”is opened，Unable to display the number of files
![image](https://user-images.githubusercontent.com/1827701/216753349-d1ee0702-a348-4662-a2f3-6e81522406bc.png)

![image](https://user-images.githubusercontent.com/1827701/216753397-37c6b88e-de73-4122-94bf-ba58eac0afe9.png)
When I close it, it will display the number of files correctly.

**Comment by AnubisNekhet** [comment]
I've pushed an update which revamps floating titles and it should show the tooltip now onwards.

**Comment by i-iooi-i** [comment]
> I've pushed an update which revamps floating titles and it should show the tooltip now onwards.

Thank you very much. It seems to be working normally now. It's the best theme. 👍
