### ISSUE TITLE
[Bug] Unable to customize color for close button in win system

### ISSUE THREAD

**Issue by i-iooi-i** [AnubisNekhet/AnuPpuccin#72]
![Snipaste_2023-02-06_21-49-45](https://user-images.githubusercontent.com/1827701/216989191-fcba8888-e20f-469e-924d-a578b88196a8.png)

Hi, I'm here again. 😂
When using the theme, I accidentally found a small error.
When the tab color is customized on the win system, the color of the switch button is not specified together.
I tested on multiple win devices and all had the same problem.
Thank you. ❣️

**Comment by AnubisNekhet** [comment]
Hi there, I can't really resolve this issue by myself since I use MacOS. Could you please:
1. Toggle developer tools (`Ctrl + Shift + i`) 
2. Click on the following icon:
<img width="21" alt="image" src="https://user-images.githubusercontent.com/102488279/217000117-7bc7dcc2-80aa-4022-9a52-a5434d1dc82a.png">
3. Select the object that needs recoloring

4. Send a screenshot of the developer tools window

**Comment by i-iooi-i** [comment]
![image](https://user-images.githubusercontent.com/1827701/217003887-3bbb5f1e-a7eb-48b7-afd0-5a0ff096fbbf.png)
![image](https://user-images.githubusercontent.com/1827701/217004825-c3f60774-44ed-4339-8900-0bad459b60cc.png)

Hello,
Please see if this is what you want. I selected these three items in the yellow box. They correspond to "maximize", "minimize" and "close" respectively.
Please~

**Comment by AnubisNekhet** [comment]
Thank you so much, that is exactly what I wanted!

**Comment by AnubisNekhet** [comment]
Aaand it's fixed! 🎉
The latest commit fixes the background color issue to allow custom colors.

**Comment by i-iooi-i** [comment]
> Aaand it's fixed! 🎉 The latest commit fixes the background color issue to allow custom colors.

![image](https://user-images.githubusercontent.com/1827701/217031505-68f0a2bf-c23e-4e27-ad3a-7d0d42117e05.png)
![image](https://user-images.githubusercontent.com/1827701/217031671-fead4312-af06-4ff5-aa0b-50bc9dc2fb5a.png)

The efficiency is really amazing. 🌟
However, I tried to replace the latest "theme. css" file. It seems that the appearance does not take effect.
Do I need any other settings?

**Comment by AnubisNekhet** [comment]
Ah my bad haha :P
I forgot to build the CSS, it should work now.

**Comment by i-iooi-i** [comment]
> Ah my bad haha :P I forgot to build the CSS, it should work now.
![image](https://user-images.githubusercontent.com/1827701/217049505-d720cbba-b8f7-4a87-bafe-144fee582869.png)
It's perfect now. Ha ha ha, it's an interesting theme. I played it all day. 😍😍

**Comment by AnubisNekhet** [comment]
Implemented with v1.3.0
