### ISSUE TITLE
[Bug] Metadata Error on Obsidian for iPadOS

### ISSUE THREAD

**Issue by ProudBenzene** [AnubisNekhet/AnuPpuccin#73]
Hello! I found that on my iPad, it seems that there would always been two metadata blocks, one could be hidden by the _hide-metadata_ cssclass or just the button, and the other (the above one) could not be hidden at all. Are there any way to solve the problem please? Thank you!

![DnyWH6](https://figure-bed123.oss-cn-beijing.aliyuncs.com/DnyWH6.png)

**Comment by AnubisNekhet** [comment]
Could you share the raw markdown as a screenshot?

**Comment by ProudBenzene** [comment]
> Could you share the raw markdown as a screenshot?

![](https://figure-bed123.oss-cn-beijing.aliyuncs.com/202302070237571.png)

Is this photo okay?

**Comment by ProudBenzene** [comment]
> Could you share the raw markdown as a screenshot?

You said "screenshot", do you mean the snapshot of File recovery in Obsidian core plugins please?🤔

**Comment by AnubisNekhet** [comment]
Nope, just a screenshot like you sent in your original message. I don't particularly know how obsidian renders metadata in iPadOS so it might give me an insight.

**Comment by ProudBenzene** [comment]
Is this photo okay?

![IMG_4813](https://user-images.githubusercontent.com/93238080/217158355-6f959f21-087c-4b76-abf9-e2412c8f5c07.jpeg)

**Comment by ProudBenzene** [comment]
I 've found  the point. In the editor settings on iPadOS, if I toggle "show frontmatter", there will be two blocks of metadata. But if I don't toggle it, there will only be one metadata block.

**Comment by trainbuffer** [comment]
Metadata seems in flux and different between the public desktop and mobile releases at the moment. Maybe hold off on any big changes until the next public Obsidian releases.

**Comment by ProudBenzene** [comment]
> Metadata seems in flux and different between the public desktop and mobile releases at the moment. Maybe hold off on any big changes until the next public Obsidian releases.

Okay, thank you for your answer!

**Comment by trainbuffer** [comment]
@ProudBenzene I agree metadata blocks need fixing, but metadata is weird all over Obsidian at the moment 🤒🤕.  Just saying you and Anubis shouldn't waste too much time on troubleshooting or fixing until things settle down.

**Comment by ProudBenzene** [comment]
I have reported the bug in the [Forum](https://forum.obsidian.md/t/bug-metadata-error-on-obsidian-for-ipados/54432), and get the answer that in the next release the problem should be solved. Thank you for all your help!
