### ISSUE TITLE
[Feature Request] Standalone Print theme can be choosed

### ISSUE THREAD

**Issue by emisjerry** [AnubisNekhet/AnuPpuccin#76]
Hi,

Now the print (generating PDF) follows current using theme mode.
Could you add an option to choose another light/dark mode when printing?

I'm using Dark mode on screen, and wish print in Light mode.

Thanks.

**Comment by aquatix** [comment]
I found some interesting information [here](https://forum.obsidian.md/t/a-pdf-stylesheet-example/31345/2) that could help with creating a print stylesheet. Printing in some kind of Light mode would have my preference too.

**Comment by AnubisNekhet** [comment]
Fixed with v1.4.1
