### ISSUE TITLE
[Bug] Extended Colorschemes wont show up in Style settings

### ISSUE THREAD

**Issue by sidpatkar** [AnubisNekhet/AnuPpuccin#77]
**Describe the bug**
I tried installing the extended-colorschemes after downloading the theme from the Obsidian app itself. I don't see more colorscheme options in the Style settings despite it. 

**To Reproduce**
1. Go to snippets folder and add the colorschemes css.
2. Click on Style settings.
3. Open the Colors option under AnuPpuccin.
4. See error.

**Expected behavior**
See more theme flavors than just the basic ones. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9652708/217956178-e6e9a552-70b7-4ab0-b2b6-097ec981d144.png)
![image](https://user-images.githubusercontent.com/9652708/217956277-6ae513a3-fdc1-4c7a-8306-8fe54f22313f.png)

EDIT: removed unecessary info in screenshots.

**Comment by wc8** [comment]
Any solution for this?
