### ISSUE TITLE
[Bug] File Icons (sorry if this is user error)

### ISSUE THREAD

**Issue by ms3056** [AnubisNekhet/AnuPpuccin#8]
**Describe the bug**
I "believe" you have folded in code to show icons for files by filetype. I cannot see the setting to turn this on (apologies if this is my mistake). Image attached. 
![image](https://user-images.githubusercontent.com/23712700/209033358-fa5461aa-4ff9-4b95-b0bc-394ae548bb92.png)

**Comment by AnubisNekhet** [comment]
The setting should still be available in the latest release. Can you send a screenshot of your current settings?
<img width="714" alt="image" src="https://user-images.githubusercontent.com/102488279/209220134-c8f8d4f9-96aa-4bd6-89cb-37d139378e29.png">

**Comment by ms3056** [comment]
The problem seems to have been on my end. I was using BRAT to install the theme and it seems it was not updating it after you made changes. Apologies! Operator error it is!
