### ISSUE TITLE
[Bug] Header Font Not Showing in Live Preview or Source Mode

### ISSUE THREAD

**Issue by melnhh** [AnubisNekhet/AnuPpuccin#81]
**Describe the bug**
When picking a different font for my headers, the font only appears in Reading View but not Live Preview or Source Mode. This is just since the recent update.

**Expected behavior**
The font should always show, regardless of which viewing mode it's in.

**Screenshots**
Live Preview
<img width="879" alt="live preview" src="https://user-images.githubusercontent.com/116525296/217995154-df84f5ab-86eb-4563-9ef5-5ceac9338dc8.png">

Reading View
<img width="911" alt="reading view" src="https://user-images.githubusercontent.com/116525296/217995204-b7958409-a037-46a2-8804-beb49f0dae98.png">

**Comment by AnubisNekhet** [comment]
That setting is intentional for source mode, however I will change Live Preview to follow Reading Mode in the next update. Thank you for spotting it out!

**Comment by AnubisNekhet** [comment]
Implemented with v1.4.0!
