### ISSUE TITLE
Margins on PDF Export 

### ISSUE THREAD

**Issue by ArtemisFowl-San** [AnubisNekhet/AnuPpuccin#82]
**Describe the bug**
On PDF export I get some white margins. 

**To Reproduce**
1. Chose Theme
2. Export as PDF

**Expected behavior**
The background should be filled with the color from the theme for visual consistency. 

**Screenshots**
![image](https://user-images.githubusercontent.com/72747914/218177341-a637b2c5-1d53-4589-9a92-67d80abcaa5f.png)

**Additional context**
I am not sure if this behavior is normal and is just how the pdf export works, but would be great to have the background be consistent.

**Comment by AnubisNekhet** [comment]
PDF Margins cannot be manipulated solely by CSS by extension, this theme itself. If anyone has any ideas on how to go around this, feel free to make a PR.
