### ISSUE TITLE
When editing notes in Canvas, the note will appear in light mode [Bug] 

### ISSUE THREAD

**Issue by bassamsdata** [AnubisNekhet/AnuPpuccin#9]
**Describe the bug**
When I add an existing note to canvas and then try to edit it, the note switches to light theme and vice versa. 

**To Reproduce**
1. add a note to canvas.
2. try to edit the note inside canvas.
3. the note immediately switch to light theme

**Expected behavior**
the note should stay in the selected theme whether light or dark theme.

**Screenshots**
video for the issue: 🫣
https://user-images.githubusercontent.com/105807570/209048290-3637e5a0-ee48-43ad-917e-023d77d1908b.mp4

**Additional context**
- If using light theme, the note will switch to dark theme :(
- This issue doesn't happen with other themes.
Really Appreciate your work on this theme (best theme ever). Thanks a lot 🙏

**Comment by AnubisNekhet** [comment]
Sorry, I can't reproduce it on my end. Can you send your style settings JSON?

**Comment by bassamsdata** [comment]
Sure, here is the file.
[style-settings.json.zip](https://github.com/AnubisNekhet/AnuPpuccin/files/10290211/style-settings.json.zip)

I disabled all the css snippets that I have but unfortunately the issue persist.

**Comment by AnubisNekhet** [comment]
Fixed the issue with the latest commit, it was due to the background fix toggle for layouts :)

**Comment by bassamsdata** [comment]
Thank you  🙏 appreciated!
