### ISSUE TITLE
Callout collapsible icon right next to the title instead of right end

### ISSUE THREAD

**Issue by Missionary-OSBS** [AnubisNekhet/AnuPpuccin#91]
**Feature Description**
Callout collapsible icon is placed far right end instead of being right next to the title in ITS theme. It leads to confusion to identify which one is collapsible, especially when I hide all the side bars and it take some effort to keep looking at the far right end all the time to check. 

- _Callout: Vanilla style from AnuPpuccin theme_
![2023-02-21_20 54 49_CSX](https://user-images.githubusercontent.com/98799613/220525830-6c237bec-4381-43b3-8d65-84779cdc2f2c.jpg)

- _Callout from ITS theme_
![2023-02-21_20 55 07_CSX](https://user-images.githubusercontent.com/98799613/220525967-28b5d9f1-4c24-4c9e-9762-c75c2b8d2796.jpg)

**Comment by AnubisNekhet** [comment]
I've overhauled callouts with the latest update and the collapse icon position can be toggled via `File Editor & Markdown Components > Callouts > Callout Fold Position`
This change will come bundled with the next release.

**Comment by Missionary-OSBS** [comment]
It doesn't change the position of the toggle arrow...

**Comment by AnubisNekhet** [comment]
Fixed with v1.4.0!
