### ISSUE TITLE
Code Color

### ISSUE THREAD

**Issue by Missionary-OSBS** [AnubisNekhet/AnuPpuccin#92]
**Feature Description**
It would be great to have Code Color in Typography > Text Decoration. I get used to the green code color from my customizable ITS theme. 

Thank you.

**Comment by AnubisNekhet** [comment]
Codeblock colors can be changed in `File Editor & Markdown Elements -> Codeblocks -> Codeblock text color`.

**Comment by Missionary-OSBS** [comment]
Oh yeah I didn't realize that. I thought it was for codeblock not for code text. Thanks!
