### ISSUE TITLE
[Feature Request] add inline code style settings

### ISSUE THREAD

**Issue by biukang** [AnubisNekhet/AnuPpuccin#99]
In the dark mode，inline code background is black，i hope inline code can show like hightlight, 
Are there any plans to add a inline code style settings feature
![image](https://user-images.githubusercontent.com/28825931/221506762-71de8e3c-7721-4339-8503-d7c2f42e7950.png)

**Comment by AnubisNekhet** [comment]
Inline code does not have highlights, though you can change color via Markdown Elements > Codeblocks > Codeblock text color

**Comment by biukang** [comment]
Thank you!
I get it, but if i use Codeblock text color , the code block will  be changed follow with it.
other theme may provide a  extra setting to set code inline style and font, if you have time.
